// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_propagate_method_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, ok, read, Propagate, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    class Holder {
      read(input: number) {
        try {
          unwrap(/*call*/read(/*arg*/risky(/*operand*/input)));
          return ok("checked");
        } catch (error) {
          return caught(error);
        }
      }
    }
    return new Holder().read(input);
  } catch (error) {
    if (error instanceof Propagate) throw error;
    return ok(note("caught", (error as Error).message));
  }
}
