// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_propagate_resultBody_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    try {
      const block = (() => {
          try {
            const base = unwrap(read(note("base", 1)));
            unwrap(/*call*/read(/*arg*/note("operand", /*operand*/input)));
            return ok([base, "checked"]);
          } catch (error) {
            return caught(error);
          }
      })();
      return ok(block);
    } finally {
      note("finally", 0);
    }
  } catch (error) {
    return caught(error);
  }
}
