// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_declaration_whileBody_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [5, -5];
function probe(input: number) {
  try {
    using res = resource("res");
    let collected: unknown = "none";
    while (note("test", true)) {
      const /*bind*/checked = unwrap(/*call*/read(note("operand", /*operand*/input)));
      collected = checked;
      break;
    }
    return ok(collected);
  } catch (error) {
    return caught(error);
  }
}
