// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_declaration_functionBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { later, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [5, -5];
async function probe(input: number) {
  try {
    const /*bind*/checked = unwrap(/*call*/read(await later(/*operand*/input)));
    return ok(checked);
  } catch (error) {
    return caught(error);
  }
}
