// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_propagate_componentBody_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, first, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  function Card(props: { input: number }) {
    try {
      const input = props./*memberProps*/input;
      unwrap(/*call*/read(/*arg*/first(...[/*operand*/input])));
      return ok(<p>{text("checked")}</p>);
    } catch (error) {
      return caught(error);
    }
  }
  return Card({ input });
}
