// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_propagate_labeledBlock_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    let collected: unknown = "none";
    found: {
      unwrap(/*call*/read(/*arg*/box(/*operand*/input)?.inner.value!));
      collected = "checked";
    }
    return ok(collected);
  } catch (error) {
    return caught(error);
  }
}
