// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_declaration_matchBlockArm_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [5, -5];
function probe(input: number) {
  try {
    try {
      note<boolean>("arm", true);
      const value = (() => {
          const /*bind*/checked = unwrap(/*call*/read(note("operand", /*operand*/input)));
          return checked;
      })();
      return ok(value);
    } finally {
      note("finally", 0);
    }
  } catch (error) {
    return caught(error);
  }
}
