// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_declaration_componentBody_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, later, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [5, -5];
function probe(input: number) {
  async function Card(props: { input: number }) {
    try {
      const input = props./*memberProps*/input;
      const /*bind*/checked = unwrap(/*call*/read(await later(/*operand*/input)));
      return ok(<p>{text(checked)}</p>);
    } catch (error) {
      return caught(error);
    }
  }
  return Card({ input });
}
