// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_propagate_matchBlockArm_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
async function probe(input: number) {
  try {
    note<boolean>("arm", true);
    const value = (await (async () => {
          unwrap(/*call*/read(/*arg*/await later(/*operand*/input)));
          return "checked";
      })());
    return ok(value);
  } catch (error) {
    return caught(error);
  }
}
