// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_propagate_ifBranch_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    if (note("enter", true)) {
      unwrap(/*call*/read(/*arg*/first(...[/*operand*/input])));
      return ok("checked");
    }
    return ok("skipped");
  } catch (error) {
    return caught(error);
  }
}
