// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_propagate_catchBlock_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, ok, read, Propagate, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
async function probe(input: number) {
  try {
    try {
      throw new Error(note("throw", "boom"));
    } catch (error) {
      if (error instanceof Propagate) throw error;
      unwrap(/*call*/read(/*arg*/await later(/*operand*/input)));
      return ok("checked");
    }
  } catch (error) {
    return caught(error);
  }
}
