// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_propagate_tryBlock_spread.tt; it shares the case's other units.
// @filename: main.ts
import { first, ok, read, Propagate, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    try {
      unwrap(/*call*/read(/*arg*/first(...[/*operand*/input])));
      return ok("checked");
    } catch (error) {
      if (error instanceof Propagate) throw error;
      return ok("caught");
    }
  } catch (error) {
    return caught(error);
  }
}
