// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_propagate_method_await.tt; it shares the case's other units.
// @filename: main.ts
import { later, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  class Holder {
    async read(input: number) {
      try {
        unwrap(/*call*/read(/*arg*/await later(/*operand*/input)));
        return ok("checked");
      } catch (error) {
        return caught(error);
      }
    }
  }
  return new Holder().read(input);
}
