// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_declaration_componentBody_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, risky, ok, read, Propagate, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [5, -5];
function probe(input: number) {
  try {
    function Card(props: { input: number }) {
      try {
        const input = props./*memberProps*/input;
        const /*bind*/checked = unwrap(/*call*/read(risky(/*operand*/input)));
        return ok(<p>{text(checked)}</p>);
      } catch (error) {
        return caught(error);
      }
    }
    return Card({ input });
  } catch (error) {
    if (error instanceof Propagate) throw error;
    return ok(note("caught", (error as Error).message));
  }
}
