// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of tryStatement_propagate_forOfBody_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    const collected: unknown[] = [];
    for (const round of [0, 1]) {
      note("round", round);
      unwrap(/*call*/read(/*arg*/note("operand", /*operand*/input)));
      collected.push("checked");
    }
    return ok(collected);
  } catch (error) {
    return caught(error);
  }
}
