// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_catchBinding_ifBranch_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  try {
    if (note("enter", true)) {
      let seen: unknown = null;
      try {
        throw { n: risky(/*operand*/input) };
      } catch (/*bind*/e) {
        seen = note("caught", /*use*/e);
      }
      return seen;
    }
    return "skipped";
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
