// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_originalMutated_method_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, read } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  using res = resource("res");
  class Holder {
    read(input: number) {
      const /*bind2*/original = { n: note("operand", /*operand*/input) };
      const /*bind*/view = /*use2*/original;
      original.n = note("original", original.n + 10);
      const seen = /*use*/view./*member*/n;
      return seen;
    }
  }
  return new Holder().read(input);
}
