// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_parameter_labeledBlock_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  let collected: unknown = "none";
  found: {
    function readN(/*bind*/p: { n: number }) {
      return note("param", /*use*/p./*member*/n);
    }
    const seen = /*call*/readN(/*arg*/{ n: box(/*operand*/input)?.inner.value! });
    collected = seen;
  }
  return collected;
}
