// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_spreadCopy_arrowBlock_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  using res = resource("res");
  const inner = (input: number) => {
    const /*bind*/cfg = { n: note("operand", /*operand*/input) };
    const /*bind2*/copy = { .../*use*/cfg };
    copy.n = note("copy", /*use2*/copy./*member*/n + 1);
    const seen = [cfg.n, copy.n];
    return seen;
  };
  return inner(input);
}
