// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_letRebound_labeledBlock_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  using res = resource("res");
  let collected: unknown = "none";
  found: {
    let /*bind*/state = { n: note("operand", /*operand*/input) };
    state = { n: /*use*/state./*member*/n * 2 };
    const seen = state.n;
    collected = seen;
  }
  return collected;
}
