// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_passedToValParameter_tryBlock_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  using res = resource("res");
  try {
    const show = (/*bind*/p: { n: number }) => note("show", /*use*/p.n);
    const /*bind2*/cfg = { n: note("operand", /*operand*/input) };
    const seen = /*call*/show(/*use2*/cfg);
    return seen;
  } catch (error) {
    return "caught";
  }
}
