// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_forOfBinding_arrowBlock_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  try {
    const inner = (input: number) => {
      let seen = 0;
      for (const /*bind*/item of [{ n: risky(/*operand*/input) }, { n: 1 }]) {
        seen += note("item", /*use*/item./*member*/n);
      }
      return seen;
    };
    return inner(input);
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
