// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_forOfBinding_topLevel_using.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, resource, report } from "./harness.js";
const inputs: number[] = [3, 8];
let input: number = inputs[0]!;
using res = resource("res");
let seen = 0;
for (const /*bind*/item of [{ n: note("operand", /*operand*/input) }, { n: 1 }]) {
  seen += note("item", /*use*/item./*member*/n);
}
report("topLevel", input, text(seen));
