// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_catchBinding_resultBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [3, 8];
async function probe(input: number) {
  const block = (await (async () => {
        try {
          const base = unwrap(read(note("base", 1)));
          let seen: unknown = null;
          try {
            throw { n: await later(/*operand*/input) };
          } catch (/*bind*/e) {
            seen = note("caught", /*use*/e);
          }
          return ok([base, seen]);
        } catch (error) {
          return caught(error);
        }
    })());
  return block;
}
