// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_passedToValParameter_forOfBody_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [3, 8];
function* probe(input: number): Generator<unknown, unknown, number> {
  const collected: unknown[] = [];
  for (const round of [0, 1]) {
    note("round", round);
    const show = (/*bind*/p: { n: number }) => note("show", /*use*/p.n);
    const /*bind2*/cfg = { n: (yield /*operand*/input) };
    const seen = /*call*/show(/*use2*/cfg);
    collected.push(seen);
  }
  return collected;
}
