// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_constObject_forOfBody_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  const collected: unknown[] = [];
  for (const round of [0, 1]) {
    note("round", round);
    const /*bind*/cfg = { n: box(/*operand*/input)?.inner.value!, inner: { m: 1 } };
    const seen = note("read", /*use*/cfg./*member*/n + cfg.inner.m);
    collected.push(seen);
  }
  return collected;
}
