// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_forOfBinding_tryBlock_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  try {
    let seen = 0;
    for (const /*bind*/item of [{ n: first(...[/*operand*/input]) }, { n: 1 }]) {
      seen += note("item", /*use*/item./*member*/n);
    }
    return seen;
  } catch (error) {
    return "caught";
  }
}
