// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_originalMutated_forOfBody_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  try {
    const collected: unknown[] = [];
    for (const round of [0, 1]) {
      note("round", round);
      const /*bind2*/original = { n: note("operand", /*operand*/input) };
      const /*bind*/view = /*use2*/original;
      original.n = note("original", original.n + 10);
      const seen = /*use*/view./*member*/n;
      collected.push(seen);
    }
    return collected;
  } finally {
    note("finally", 0);
  }
}
