// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_catchBinding_nestedBlock_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  {
    let seen: unknown = null;
    try {
      throw { n: box(/*operand*/input)?.inner.value! };
    } catch (/*bind*/e) {
      seen = note("caught", /*use*/e);
    }
    return seen;
  }
}
