// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_spreadCopy_switchClause_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [3, 8];
function* probe(input: number): Generator<unknown, unknown, number> {
  switch (note("discriminant", 1)) {
    case 1: {
      const /*bind*/cfg = { n: (yield /*operand*/input) };
      const /*bind2*/copy = { .../*use*/cfg };
      copy.n = note("copy", /*use2*/copy./*member*/n + 1);
      const seen = [cfg.n, copy.n];
      return seen;
    }
    default:
    return "default";
  }
}
