// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_spreadCopy_method_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, read } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  class Holder {
    read(input: number) {
      const /*bind*/cfg = { n: first(...[/*operand*/input]) };
      const /*bind2*/copy = { .../*use*/cfg };
      copy.n = note("copy", /*use2*/copy./*member*/n + 1);
      const seen = [cfg.n, copy.n];
      return seen;
    }
  }
  return new Holder().read(input);
}
