// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_forOfBinding_functionBody_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  let seen = 0;
  for (const /*bind*/item of [{ n: box(/*operand*/input)?.inner.value! }, { n: 1 }]) {
    seen += note("item", /*use*/item./*member*/n);
  }
  return seen;
}
