// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_letRebound_ifBranch_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later } from "./harness.js";
const inputs: number[] = [3, 8];
async function probe(input: number) {
  if (note("enter", true)) {
    let /*bind*/state = { n: await later(/*operand*/input) };
    state = { n: /*use*/state./*member*/n * 2 };
    const seen = state.n;
    return seen;
  }
  return "skipped";
}
