// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_constObject_whileBody_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  let collected: unknown = "none";
  while (note("test", true)) {
    const /*bind*/cfg = { n: first(...[/*operand*/input]), inner: { m: 1 } };
    const seen = note("read", /*use*/cfg./*member*/n + cfg.inner.m);
    collected = seen;
    break;
  }
  return collected;
}
