// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_parameter_whileBody_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  using res = resource("res");
  let collected: unknown = "none";
  while (note("test", true)) {
    function readN(/*bind*/p: { n: number }) {
      return note("param", /*use*/p./*member*/n);
    }
    const seen = /*call*/readN(/*arg*/{ n: note("operand", /*operand*/input) });
    collected = seen;
    break;
  }
  return collected;
}
