// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_pipedToValParameter_labeledBlock_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  let collected: unknown = "none";
  found: {
    const show = (/*bind*/p: { n: number }) => note("show", /*use*/p.n);
    const /*bind2*/cfg = { n: box(/*operand*/input)?.inner.value! };
    const seen = /*call*/show(/*use2*/cfg);
    collected = seen;
  }
  return collected;
}
