// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_catchBinding_whileBody_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  try {
    let collected: unknown = "none";
    while (note("test", true)) {
      let seen: unknown = null;
      try {
        throw { n: note("operand", /*operand*/input) };
      } catch (/*bind*/e) {
        seen = note("caught", /*use*/e);
      }
      collected = seen;
      break;
    }
    return collected;
  } finally {
    note("finally", 0);
  }
}
