// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_parameter_catchBlock_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [3, 8];
function* probe(input: number): Generator<unknown, unknown, number> {
  try {
    throw new Error(note("throw", "boom"));
  } catch (error) {
    function readN(/*bind*/p: { n: number }) {
      return note("param", /*use*/p./*member*/n);
    }
    const seen = /*call*/readN(/*arg*/{ n: (yield /*operand*/input) });
    return seen;
  }
}
