// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_constObject_switchClause_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later } from "./harness.js";
const inputs: number[] = [3, 8];
async function probe(input: number) {
  switch (note("discriminant", 1)) {
    case 1: {
      const /*bind*/cfg = { n: await later(/*operand*/input), inner: { m: 1 } };
      const seen = note("read", /*use*/cfg./*member*/n + cfg.inner.m);
      return seen;
    }
    default:
    return "default";
  }
}
