// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_originalMutated_ifBranch_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  if (note("enter", true)) {
    const /*bind2*/original = { n: first(...[/*operand*/input]) };
    const /*bind*/view = /*use2*/original;
    original.n = note("original", original.n + 10);
    const seen = /*use*/view./*member*/n;
    return seen;
  }
  return "skipped";
}
