// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_letRebound_method_await.tt; it shares the case's other units.
// @filename: main.ts
import { later, read } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  class Holder {
    async read(input: number) {
      let /*bind*/state = { n: await later(/*operand*/input) };
      state = { n: /*use*/state./*member*/n * 2 };
      const seen = state.n;
      return seen;
    }
  }
  return new Holder().read(input);
}
