// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_catchBinding_componentBody_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, first, element, Fragment } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    let seen: unknown = null;
    try {
      throw { n: first(...[/*operand*/input]) };
    } catch (/*bind*/e) {
      seen = note("caught", /*use*/e);
    }
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
