// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_parameter_matchBlockArm_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  note<boolean>("arm", true);
  const value = (() => {
      function readN(/*bind*/p: { n: number }) {
        return note("param", /*use*/p./*member*/n);
      }
      const seen = /*call*/readN(/*arg*/{ n: first(...[/*operand*/input]) });
      return seen;
  })();
  return value;
}
