// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_letRebound_constructorBody_spread.tt; it shares the case's other units.
// @filename: main.ts
import { first } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  class Holder {
    field: unknown = "none";
    constructor(input: number) {
      let /*bind*/state = { n: first(...[/*operand*/input]) };
      state = { n: /*use*/state./*member*/n * 2 };
      const seen = state.n;
      this.field = seen;
    }
  }
  return new Holder(input).field;
}
