// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_forOfBinding_forOfBody_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  const collected: unknown[] = [];
  for (const round of [0, 1]) {
    note("round", round);
    let seen = 0;
    for (const /*bind*/item of [{ n: note("operand", /*operand*/input) }, { n: 1 }]) {
      seen += note("item", /*use*/item./*member*/n);
    }
    collected.push(seen);
  }
  return collected;
}
