// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_letRebound_tryBlock_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  try {
    let /*bind*/state = { n: note("operand", /*operand*/input) };
    state = { n: /*use*/state./*member*/n * 2 };
    const seen = state.n;
    return seen;
  } catch (error) {
    return "caught";
  }
}
