// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_letRebound_whileBody_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  let collected: unknown = "none";
  while (note("test", true)) {
    let /*bind*/state = { n: box(/*operand*/input)?.inner.value! };
    state = { n: /*use*/state./*member*/n * 2 };
    const seen = state.n;
    collected = seen;
    break;
  }
  return collected;
}
