// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_spreadCopy_functionBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  try {
    const /*bind*/cfg = { n: risky(/*operand*/input) };
    const /*bind2*/copy = { .../*use*/cfg };
    copy.n = note("copy", /*use2*/copy./*member*/n + 1);
    const seen = [cfg.n, copy.n];
    return seen;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
