// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_catchBinding_forOfBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later } from "./harness.js";
const inputs: number[] = [3, 8];
async function probe(input: number) {
  const collected: unknown[] = [];
  for (const round of [0, 1]) {
    note("round", round);
    let seen: unknown = null;
    try {
      throw { n: await later(/*operand*/input) };
    } catch (/*bind*/e) {
      seen = note("caught", /*use*/e);
    }
    collected.push(seen);
  }
  return collected;
}
