// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_forOfBinding_switchClause_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  try {
    switch (note("discriminant", 1)) {
      case 1: {
        let seen = 0;
        for (const /*bind*/item of [{ n: note("operand", /*operand*/input) }, { n: 1 }]) {
          seen += note("item", /*use*/item./*member*/n);
        }
        return seen;
      }
      default:
      return "default";
    }
  } finally {
    note("finally", 0);
  }
}
