// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_letRebound_componentBody_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, later, element, Fragment } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  async function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    let /*bind*/state = { n: await later(/*operand*/input) };
    state = { n: /*use*/state./*member*/n * 2 };
    const seen = state.n;
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
