// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_pipedToValParameter_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, report } from "./harness.js";
const inputs: number[] = [3, 8];
let input: number = inputs[0]!;
const show = (/*bind*/p: { n: number }) => note("show", /*use*/p.n);
const /*bind2*/cfg = { n: await later(/*operand*/input) };
const seen = /*call*/show(/*use2*/cfg);
report("topLevel", input, text(seen));
