// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_spreadCopy_componentBody_optionalChain.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, box, element, Fragment } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    const /*bind*/cfg = { n: box(/*operand*/input)?.inner.value! };
    const /*bind2*/copy = { .../*use*/cfg };
    copy.n = note("copy", /*use2*/copy./*member*/n + 1);
    const seen = [cfg.n, copy.n];
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
