// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_parameter_resultBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  try {
    const block = (() => {
        try {
          const base = unwrap(read(note("base", 1)));
          function readN(/*bind*/p: { n: number }) {
            return note("param", /*use*/p./*member*/n);
          }
          const seen = /*call*/readN(/*arg*/{ n: risky(/*operand*/input) });
          return ok([base, seen]);
        } catch (error) {
          return caught(error);
        }
    })();
    return block;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
