// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_passedToValParameter_resultBody_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  const block = (() => {
      try {
        const base = unwrap(read(note("base", 1)));
        const show = (/*bind*/p: { n: number }) => note("show", /*use*/p.n);
        const /*bind2*/cfg = { n: first(...[/*operand*/input]) };
        const seen = /*call*/show(/*use2*/cfg);
        return ok([base, seen]);
      } catch (error) {
        return caught(error);
      }
  })();
  return block;
}
