// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_originalMutated_componentBody_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, later, element, Fragment } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  async function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    const /*bind2*/original = { n: await later(/*operand*/input) };
    const /*bind*/view = /*use2*/original;
    original.n = note("original", original.n + 10);
    const seen = /*use*/view./*member*/n;
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
