// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_forOfBinding_componentBody_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, element, Fragment } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  try {
    function Card(props: { input: number }) {
      const input = props./*memberProps*/input;
      let seen = 0;
      for (const /*bind*/item of [{ n: note("operand", /*operand*/input) }, { n: 1 }]) {
        seen += note("item", /*use*/item./*member*/n);
      }
      return <p>{text(seen)}</p>;
    }
    return Card({ input });
  } finally {
    note("finally", 0);
  }
}
