// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_forOfBinding_whileBody_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [3, 8];
function* probe(input: number): Generator<unknown, unknown, number> {
  let collected: unknown = "none";
  while (note("test", true)) {
    let seen = 0;
    for (const /*bind*/item of [{ n: (yield /*operand*/input) }, { n: 1 }]) {
      seen += note("item", /*use*/item./*member*/n);
    }
    collected = seen;
    break;
  }
  return collected;
}
