// Generated by scripts/generate-cases from tests/matrix/val.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of val_letRebound_catchBlock_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [3, 8];
function probe(input: number) {
  try {
    try {
      throw new Error(note("throw", "boom"));
    } catch (error) {
      let /*bind*/state = { n: note("operand", /*operand*/input) };
      state = { n: /*use*/state./*member*/n * 2 };
      const seen = state.n;
      return seen;
    }
  } finally {
    note("finally", 0);
  }
}
