// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_throwingElse_topLevel_spread.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, first, read, report } from "./harness.js";
const inputs: number[] = [5, -5];
let input: number = inputs[0]!;
const t0 = read(first(...[/*operand*/input]));
if (t0.kind !== "Ok") { throw new /*call*/Error(/*arg*/note("else", "thrown")); }
const /*bind*/v = t0.value;
report("topLevel", input, text(v));
