// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_let_labeledBlock_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, read } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  try {
    let collected: unknown = "none";
    found: {
      const t0 = read(note("operand", /*operand*/input));
      if (t0.kind !== "Ok") { break found; }
      let /*bind*/v = t0.value;
      v = note("reassigned", /*use*/v + 1);
      collected = v;
    }
    return collected;
  } finally {
    note("finally", 0);
  }
}
