// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_let_arrowBlock_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, read } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  const inner = (input: number) => {
    const t0 = read(first(...[/*operand*/input]));
    if (t0.kind !== "Ok") { return "diverged"; }
    let /*bind*/v = t0.value;
    v = note("reassigned", /*use*/v + 1);
    return v;
  };
  return inner(input);
}
