// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_let_componentBody_plain.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, read, element, Fragment } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    const t0 = read(note("operand", /*operand*/input));
    if (t0.kind !== "Ok") { return <p>diverged</p>; }
    let /*bind*/v = t0.value;
    v = note("reassigned", /*use*/v + 1);
    return <p>{text(v)}</p>;
  }
  return Card({ input });
}
