// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_var_resultBodyTemplateExit_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  using res = resource("res");
  const block = (() => {
      try {
        const base = unwrap(read(note("base", 1)));
        const t0 = /*call*/read(note("operand", /*operand*/input));
        if (t0.kind !== "Ok") { return ok(`<${base === 1 ? "one" : "many"}>`); }
        var /*bind*/v = t0.value;
        return ok([base, v]);
      } catch (error) {
        return caught(error);
      }
  })();
  return block;
}
