// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_aliasedFields_method_await.tt; it shares the case's other units.
// @filename: main.ts
import { later, read } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Rect(2, 3), Shape.Circle(1), Shape.Point];
function probe(input: Shape) {
  class Holder {
    async read(input: Shape) {
      const t0 = await later(/*operand*/input);
      if (t0.kind !== "Rect") { return "diverged"; }
      const { /*field*/h: /*bind*/height, w: /*bind2*/width } = t0;
      return [width, height];
    }
  }
  return new Holder().read(input);
}
