// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_var_arrowBlock_spread.tt; it shares the case's other units.
// @filename: main.ts
import { first, read } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  const inner = (input: number) => {
    const t0 = /*call*/read(first(...[/*operand*/input]));
    if (t0.kind !== "Ok") { return "diverged"; }
    var /*bind*/v = t0.value;
    return v;
  };
  return inner(input);
}
