// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_var_unbracedIf_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, read } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  try {
    if (note("enter", true)) { const t0 = /*call*/read(risky(/*operand*/input));
      if (t0.kind !== "Ok") { return "diverged"; }
      var /*bind*/v = t0.value; }
    return v!;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
