// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_let_constructorBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, read } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  try {
    class Holder {
      field: unknown = "none";
      constructor(input: number) {
        const t0 = read(risky(/*operand*/input));
        if (t0.kind !== "Ok") { throw new Error("diverged"); }
        let /*bind*/v = t0.value;
        v = note("reassigned", /*use*/v + 1);
        this.field = v;
      }
    }
    return new Holder(input).field;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
