// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_var_constructorBody_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, read } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  try {
    class Holder {
      field: unknown = "none";
      constructor(input: number) {
        const t0 = /*call*/read(note("operand", /*operand*/input));
        if (t0.kind !== "Ok") { throw new Error("diverged"); }
        var /*bind*/v = t0.value;
        this.field = v;
      }
    }
    return new Holder(input).field;
  } finally {
    note("finally", 0);
  }
}
