// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_var_resultBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [4, -4];
async function probe(input: number) {
  const block = (await (async () => {
        try {
          const base = unwrap(read(note("base", 1)));
          const t0 = /*call*/read(await later(/*operand*/input));
          if (t0.kind !== "Ok") { return ok(base); }
          var /*bind*/v = t0.value;
          return ok([base, v]);
        } catch (error) {
          return caught(error);
        }
    })());
  return block;
}
