// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_objectInitializer_ifBranch_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource } from "./harness.js";
const inputs: number[] = [7, 8];
function probe(input: number) {
  using res = resource("res");
  if (note("enter", true)) {
    const t0 = { kind: "Some" as const, value: note("operand", /*operand*/input) };
    if (t0.kind !== "Some") { return "diverged"; }
    const /*bind*/v = t0.value;
    return v;
  }
  return "skipped";
}
