// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_throwingElse_staticBlock_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, read } from "./harness.js";
const inputs: number[] = [5, -5];
function probe(input: number) {
  class Holder {
    static field: unknown = "none";
    static {
      const t0 = read(first(...[/*operand*/input]));
      if (t0.kind !== "Ok") { throw new /*call*/Error(/*arg*/note("else", "thrown")); }
      const /*bind*/v = t0.value;
      Holder.field = v;
    }
  }
  return Holder.field;
}
