// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_let_catchBlock_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, read } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  using res = resource("res");
  try {
    throw new Error(note("throw", "boom"));
  } catch (error) {
    const t0 = read(note("operand", /*operand*/input));
    if (t0.kind !== "Ok") { return "diverged"; }
    let /*bind*/v = t0.value;
    v = note("reassigned", /*use*/v + 1);
    return v;
  }
}
