// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_const_functionBody_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, read } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  using res = resource("res");
  const t0 = /*call*/read(/*arg*/note("operand", /*operand*/input));
  if (t0.kind !== "Ok") { return "diverged"; }
  const /*bind*/v = t0./*field*/value;
  return v;
}
