// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_objectInitializer_catchBlock_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [7, 8];
function* probe(input: number): Generator<unknown, unknown, number> {
  try {
    throw new Error(note("throw", "boom"));
  } catch (error) {
    const t0 = { kind: "Some" as const, value: (yield /*operand*/input) };
    if (t0.kind !== "Some") { return "diverged"; }
    const /*bind*/v = t0.value;
    return v;
  }
}
