// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_aliasedFields_forOfBody_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Rect(2, 3), Shape.Circle(1), Shape.Point];
function probe(input: Shape) {
  try {
    const collected: unknown[] = [];
    for (const round of [0, 1]) {
      note("round", round);
      const t0 = note("operand", /*operand*/input);
      if (t0.kind !== "Rect") { continue; }
      const { /*field*/h: /*bind*/height, w: /*bind2*/width } = t0;
      collected.push([width, height]);
    }
    return collected;
  } finally {
    note("finally", 0);
  }
}
