// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_objectInitializer_staticBlock_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box } from "./harness.js";
const inputs: number[] = [7, 8];
function probe(input: number) {
  class Holder {
    static field: unknown = "none";
    static {
      const t0 = { kind: "Some" as const, value: box(/*operand*/input)?.inner.value! };
      if (t0.kind !== "Some") { throw new Error("diverged"); }
      const /*bind*/v = t0.value;
      Holder.field = v;
    }
  }
  return Holder.field;
}
