// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_var_labeledBlock_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, read } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  let collected: unknown = "none";
  found: {
    const t0 = /*call*/read(note("operand", /*operand*/input));
    if (t0.kind !== "Ok") { break found; }
    var /*bind*/v = t0.value;
    collected = v;
  }
  return collected;
}
