// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_let_whileBody_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note, read } from "./harness.js";
const inputs: number[] = [3, -3];
function* probe(input: number): Generator<unknown, unknown, number> {
  let collected: unknown = "none";
  while (note("test", true)) {
    const t0 = read((yield /*operand*/input));
    if (t0.kind !== "Ok") { break; }
    let /*bind*/v = t0.value;
    v = note("reassigned", /*use*/v + 1);
    collected = v;
    break;
  }
  return collected;
}
