// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_var_switchClause_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, read } from "./harness.js";
const inputs: number[] = [4, -4];
async function probe(input: number) {
  switch (note("discriminant", 1)) {
    case 1: {
      const t0 = /*call*/read(await later(/*operand*/input));
      if (t0.kind !== "Ok") { return "diverged"; }
      var /*bind*/v = t0.value;
      return v;
    }
    default:
    return "default";
  }
}
