// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_const_method_spread.tt; it shares the case's other units.
// @filename: main.ts
import { first, read } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  class Holder {
    read(input: number) {
      const t0 = /*call*/read(/*arg*/first(...[/*operand*/input]));
      if (t0.kind !== "Ok") { return "diverged"; }
      const /*bind*/v = t0./*field*/value;
      return v;
    }
  }
  return new Holder().read(input);
}
