// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_var_method_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, read } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  using res = resource("res");
  class Holder {
    read(input: number) {
      const t0 = /*call*/read(note("operand", /*operand*/input));
      if (t0.kind !== "Ok") { return "diverged"; }
      var /*bind*/v = t0.value;
      return v;
    }
  }
  return new Holder().read(input);
}
