// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_const_resultBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    const block = (() => {
        try {
          const base = unwrap(read(note("base", 1)));
          const t0 = /*call*/read(/*arg*/risky(/*operand*/input));
          if (t0.kind !== "Ok") { return ok(base); }
          const /*bind*/v = t0./*field*/value;
          return ok([base, v]);
        } catch (error) {
          return caught(error);
        }
    })();
    return block;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
