// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_objectInitializer_resultBodyValueExit_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [7, 8];
function probe(input: number) {
  const block = (() => {
      try {
        const base = unwrap(read(note("base", 1)));
        const t0 = { kind: "Some" as const, value: first(...[/*operand*/input]) };
        if (t0.kind !== "Some") { return ok(unwrap(read(note("exit", -7)))); }
        const /*bind*/v = t0.value;
        return ok([base, v]);
      } catch (error) {
        return caught(error);
      }
  })();
  return block;
}
