// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_throwingElse_ifBranch_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, read } from "./harness.js";
const inputs: number[] = [5, -5];
async function probe(input: number) {
  if (note("enter", true)) {
    const t0 = read(await later(/*operand*/input));
    if (t0.kind !== "Ok") { throw new /*call*/Error(/*arg*/note("else", "thrown")); }
    const /*bind*/v = t0.value;
    return v;
  }
  return "skipped";
}
