// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_objectInitializer_componentBody_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, first, element, Fragment } from "./harness.js";
const inputs: number[] = [7, 8];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    const t0 = { kind: "Some" as const, value: first(...[/*operand*/input]) };
    if (t0.kind !== "Some") { return <p>diverged</p>; }
    const /*bind*/v = t0.value;
    return <p>{text(v)}</p>;
  }
  return Card({ input });
}
