// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_const_topLevel_plain.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, read, report } from "./harness.js";
const inputs: number[] = [2, -1];
let input: number = inputs[0]!;
const t0 = /*call*/read(/*arg*/note("operand", /*operand*/input));
if (t0.kind !== "Ok") { throw new Error("diverged"); }
const /*bind*/v = t0./*field*/value;
report("topLevel", input, text(v));
