// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_var_tryBlock_yield.tt; it shares the case's other units.
// @filename: main.ts
import { read } from "./harness.js";
const inputs: number[] = [4, -4];
function* probe(input: number): Generator<unknown, unknown, number> {
  try {
    const t0 = /*call*/read((yield /*operand*/input));
    if (t0.kind !== "Ok") { return "diverged"; }
    var /*bind*/v = t0.value;
    return v;
  } catch (error) {
    return "caught";
  }
}
