// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_const_forOfBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, read } from "./harness.js";
const inputs: number[] = [2, -1];
async function probe(input: number) {
  const collected: unknown[] = [];
  for (const round of [0, 1]) {
    note("round", round);
    const t0 = /*call*/read(/*arg*/await later(/*operand*/input));
    if (t0.kind !== "Ok") { continue; }
    const /*bind*/v = t0./*field*/value;
    collected.push(v);
  }
  return collected;
}
