// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_const_catchBlock_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, read } from "./harness.js";
const inputs: number[] = [2, -1];
async function probe(input: number) {
  try {
    throw new Error(note("throw", "boom"));
  } catch (error) {
    const t0 = /*call*/read(/*arg*/await later(/*operand*/input));
    if (t0.kind !== "Ok") { return "diverged"; }
    const /*bind*/v = t0./*field*/value;
    return v;
  }
}
