// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_let_method_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box, read } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  class Holder {
    read(input: number) {
      const t0 = read(box(/*operand*/input)?.inner.value!);
      if (t0.kind !== "Ok") { return "diverged"; }
      let /*bind*/v = t0.value;
      v = note("reassigned", /*use*/v + 1);
      return v;
    }
  }
  return new Holder().read(input);
}
