// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_const_switchClause_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, read } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    switch (note("discriminant", 1)) {
      case 1: {
        const t0 = /*call*/read(/*arg*/risky(/*operand*/input));
        if (t0.kind !== "Ok") { return "diverged"; }
        const /*bind*/v = t0./*field*/value;
        return v;
      }
      default:
      return "default";
    }
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
