// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_objectInitializer_labeledBlock_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [7, 8];
function probe(input: number) {
  try {
    let collected: unknown = "none";
    found: {
      const t0 = { kind: "Some" as const, value: note("operand", /*operand*/input) };
      if (t0.kind !== "Some") { break found; }
      const /*bind*/v = t0.value;
      collected = v;
    }
    return collected;
  } finally {
    note("finally", 0);
  }
}
