// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_aliasedFields_functionBody_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Rect(2, 3), Shape.Circle(1), Shape.Point];
function probe(input: Shape) {
  using res = resource("res");
  const t0 = note("operand", /*operand*/input);
  if (t0.kind !== "Rect") { return "diverged"; }
  const { /*field*/h: /*bind*/height, w: /*bind2*/width } = t0;
  return [width, height];
}
