// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_var_nestedBlock_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box, read } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  {
    const t0 = /*call*/read(box(/*operand*/input)?.inner.value!);
    if (t0.kind !== "Ok") { return "diverged"; }
    var /*bind*/v = t0.value;
    return v;
  }
}
