// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_var_componentBody_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, later, read, element, Fragment } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  async function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    const t0 = /*call*/read(await later(/*operand*/input));
    if (t0.kind !== "Ok") { return <p>diverged</p>; }
    var /*bind*/v = t0.value;
    return <p>{text(v)}</p>;
  }
  return Card({ input });
}
