// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_let_staticBlock_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, read } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  using res = resource("res");
  class Holder {
    static field: unknown = "none";
    static {
      const t0 = read(note("operand", /*operand*/input));
      if (t0.kind !== "Ok") { throw new Error("diverged"); }
      let /*bind*/v = t0.value;
      v = note("reassigned", /*use*/v + 1);
      Holder.field = v;
    }
  }
  return Holder.field;
}
