// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_const_whileBody_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, read } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  let collected: unknown = "none";
  while (note("test", true)) {
    const t0 = /*call*/read(/*arg*/first(...[/*operand*/input]));
    if (t0.kind !== "Ok") { break; }
    const /*bind*/v = t0./*field*/value;
    collected = v;
    break;
  }
  return collected;
}
