// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_const_resultBodyValueExit_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  const block = (() => {
      try {
        const base = unwrap(read(note("base", 1)));
        const t0 = /*call*/read(/*arg*/box(/*operand*/input)?.inner.value!);
        if (t0.kind !== "Ok") { return ok(unwrap(read(note("exit", -7)))); }
        const /*bind*/v = t0./*field*/value;
        return ok([base, v]);
      } catch (error) {
        return caught(error);
      }
  })();
  return block;
}
