// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_objectInitializer_tryBlock_await.tt; it shares the case's other units.
// @filename: main.ts
import { later } from "./harness.js";
const inputs: number[] = [7, 8];
async function probe(input: number) {
  try {
    const t0 = { kind: "Some" as const, value: await later(/*operand*/input) };
    if (t0.kind !== "Some") { return "diverged"; }
    const /*bind*/v = t0.value;
    return v;
  } catch (error) {
    return "caught";
  }
}
