// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_let_resultBody_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  const block = (() => {
      try {
        const base = unwrap(read(note("base", 1)));
        const t0 = read(note("operand", /*operand*/input));
        if (t0.kind !== "Ok") { return ok(base); }
        let /*bind*/v = t0.value;
        v = note("reassigned", /*use*/v + 1);
        return ok([base, v]);
      } catch (error) {
        return caught(error);
      }
  })();
  return block;
}
