// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_orPattern_switchClause_spread.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, first } from "./harness.js";
type Token = { kind: "Num"; value: number } | { kind: "Neg"; value: number } | { kind: "Word"; text: string };
const Token = {
  Num: (value: number): Token => ({ kind: "Num" as const, value }),
  Neg: (value: number): Token => ({ kind: "Neg" as const, value }),
  Word: (text: string): Token => ({ kind: "Word" as const, text }),
};
const inputs: Token[] = [Token.Num(1), Token.Neg(-2), Token.Word("w")];
function probe(input: Token) {
  switch (note("discriminant", 1)) {
    case 1: {
      const t0 = first(...[/*operand*/input]);
      if (t0.kind !== "Num" && t0.kind !== "Neg") { return "diverged"; }
      const { /*bind*/value } = t0;
      return value;
    }
    default:
    return "default";
  }
}
