// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_let_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, read, report } from "./harness.js";
const inputs: number[] = [3, -3];
let input: number = inputs[0]!;
const t0 = read(await later(/*operand*/input));
if (t0.kind !== "Ok") { throw new Error("diverged"); }
let /*bind*/v = t0.value;
v = note("reassigned", /*use*/v + 1);
report("topLevel", input, text(v));
