// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_throwingElse_resultBody_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [5, -5];
function probe(input: number) {
  const block = (() => {
      try {
        const base = unwrap(read(note("base", 1)));
        const t0 = read(note("operand", /*operand*/input));
        if (t0.kind !== "Ok") { throw new /*call*/Error(/*arg*/note("else", "thrown")); }
        const /*bind*/v = t0.value;
        return ok([base, v]);
      } catch (error) {
        return caught(error);
      }
  })();
  return block;
}
