// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_throwingElse_constructorBody_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box, read } from "./harness.js";
const inputs: number[] = [5, -5];
function probe(input: number) {
  class Holder {
    field: unknown = "none";
    constructor(input: number) {
      const t0 = read(box(/*operand*/input)?.inner.value!);
      if (t0.kind !== "Ok") { throw new /*call*/Error(/*arg*/note("else", "thrown")); }
      const /*bind*/v = t0.value;
      this.field = v;
    }
  }
  return new Holder(input).field;
}
