// Generated by scripts/generate-cases from tests/matrix/letElse.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of letElse_objectInitializer_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, later, report } from "./harness.js";
const inputs: number[] = [7, 8];
let input: number = inputs[0]!;
const t0 = { kind: "Some" as const, value: await later(/*operand*/input) };
if (t0.kind !== "Some") { throw new Error("diverged"); }
const /*bind*/v = t0.value;
report("topLevel", input, text(v));
