// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_stringLiterals_jsxNested_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, later, element, Fragment } from "./harness.js";
let t0: any;
const inputs: string[] = ["north", "south", "east", "up"];
async function probe(input: string) {
  return <ul><li>{note("first", 1)}</li><li>{(t0 = await later(/*operand*/input), t0 === "north" ? /*call*/note(/*arg*/"n", 1) : t0 === "south" || t0 === "east" ? note("se", 2) : note("other", 0))}</li></ul>;
}
