// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_stringLiterals_method_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, read } from "./harness.js";
let t0: any;
const inputs: string[] = ["north", "south", "east", "up"];
function probe(input: string) {
  try {
    class Holder {
      tag = "holder";
      read(input: string) {
        note("this", this.tag);
        return (t0 = risky(/*operand*/input), t0 === "north" ? /*call*/note(/*arg*/"n", 1) : t0 === "south" || t0 === "east" ? note("se", 2) : note("other", 0));
      }
    }
    return new Holder().read(input);
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
