// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_tagBindings_topLevel_using.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, resource, report } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
let input: Shape = inputs[0]!;
using res = resource("res");
const top0 = ((t0: Shape) => { if (t0.kind === "Circle") { const { /*bind*/r } = t0; return note("circle", /*use*/r * 2); } if (t0.kind === "Rect") { const { w, /*bind2*/h } = t0; return /*call*/note(/*arg*/"rect", w * /*use2*/h); } return note("point", 0); })(note("operand", /*operand*/input));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((t1: Shape) => { if (t1.kind === "Circle") { const { r } = t1; return note("circle", r * 2); } if (t1.kind === "Rect") { const { w, h } = t1; return note("rect", w * h); } return note("point", 0); })(note("operand", input));
report("topLevel", input, text(top1));
input = inputs[2]!;
const top2 = ((t2: Shape) => { if (t2.kind === "Circle") { const { r } = t2; return note("circle", r * 2); } if (t2.kind === "Rect") { const { w, h } = t2; return note("rect", w * h); } return note("point", 0); })(note("operand", input));
report("topLevel", input, text(top2));
