// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_handWrittenUnion_topLevel_using.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, resource, report } from "./harness.js";
type Event = { kind: "Click"; x: number } | { kind: "Key"; key: string };
const inputs: Event[] = [{ kind: "Click", x: 3 }, { kind: "Key", key: "k" }];
let input: Event = inputs[0]!;
using res = resource("res");
const top0 = ((t0: Event) => { if (t0.kind === "Click") { const { /*bind*/x } = t0; return note("click", /*use*/x); } { const { /*bind2*/key } = t0; return note("key", /*use2*/key); } })(note("operand", /*operand*/input));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((t1: Event) => { if (t1.kind === "Click") { const { x } = t1; return note("click", x); } { const { key } = t1; return note("key", key); } })(note("operand", input));
report("topLevel", input, text(top1));
