// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_booleanLiterals_templateLiteral_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
let t0: any;
const inputs: boolean[] = [true, false];
function* probe(input: boolean): Generator<unknown, unknown, boolean> {
  return `<${note("left", "L")}|${(t0 = (yield /*operand*/input), t0 === true ? note("yes", 1) : /*call*/note(/*arg*/"no", 0))}|${note("right", "R")}>`;
}
