// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_wildcard_callArgument_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, pack } from "./harness.js";
type Token = { kind: "Num"; value: number } | { kind: "Neg"; value: number } | { kind: "Word"; text: string } | { kind: "End" };
const Token = {
  Num: (value: number): Token => ({ kind: "Num" as const, value }),
  Neg: (value: number): Token => ({ kind: "Neg" as const, value }),
  Word: (text: string): Token => ({ kind: "Word" as const, text }),
  End: { kind: "End" } as const,
};
const inputs: Token[] = [Token.Num(4), Token.Neg(-3), Token.Word("hi"), Token.End];
async function probe(input: Token) {
  return pack(note("a", 1), ((t0: Token) => { if (t0.kind === "Word") { const { /*bind*/text } = t0; return note("word", /*use*/text./*member*/length); } return note("other", -1); })(await later(/*operand*/input)), note("c", 3));
}
