// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_fieldAlias_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, report } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
let input: Shape = inputs[0]!;
const top0 = ((t0: Shape) => { if (t0.kind === "Rect") { const { /*field*/h: /*bind*/tall, w: wide } = t0; return note("rect", [wide, /*use*/tall]); } if (t0.kind === "Circle") { const { r: /*bind2*/radius } = t0; return note("circle", /*use2*/radius); } return note("point", null); })(await later(/*operand*/input));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((t1: Shape) => { if (t1.kind === "Rect") { const { h: tall, w: wide } = t1; return note("rect", [wide, tall]); } if (t1.kind === "Circle") { const { r: radius } = t1; return note("circle", radius); } return note("point", null); })(await later(input));
report("topLevel", input, text(top1));
input = inputs[2]!;
const top2 = ((t2: Shape) => { if (t2.kind === "Rect") { const { h: tall, w: wide } = t2; return note("rect", [wide, tall]); } if (t2.kind === "Circle") { const { r: radius } = t2; return note("circle", radius); } return note("point", null); })(await later(input));
report("topLevel", input, text(top2));
