// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_orPattern_nullish_exception.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, flip, risky } from "./harness.js";
type Token = { kind: "Num"; value: number } | { kind: "Neg"; value: number } | { kind: "Word"; text: string } | { kind: "End" };
const Token = {
  Num: (value: number): Token => ({ kind: "Num" as const, value }),
  Neg: (value: number): Token => ({ kind: "Neg" as const, value }),
  Word: (text: string): Token => ({ kind: "Word" as const, text }),
  End: { kind: "End" } as const,
};
const inputs: Token[] = [Token.Num(4), Token.Neg(-3), Token.Word("hi"), Token.End];
function probe(input: Token) {
  try {
    return (flip() ? null : note("left", "set")) ?? ((t0: Token) => { if (t0.kind === "Num" || t0.kind === "Neg") { const { /*bind*/value } = t0; return note("number", /*use*/value); } if (t0.kind === "Word") { const { /*bind2*/text } = t0; return note("word", /*use2*/text); } return note("end", ""); })(risky(/*operand*/input));
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
