// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_stringLiterals_jsxAttribute_using.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, resource, element, Fragment } from "./harness.js";
let t0: any;
const inputs: string[] = ["north", "south", "east", "up"];
function probe(input: string) {
  using res = resource("res");
  return <div /*attrHost*/data-value={(t0 = note("operand", /*operand*/input), t0 === "north" ? /*call*/note(/*arg*/"n", 1) : t0 === "south" || t0 === "east" ? note("se", 2) : note("other", 0))} />;
}
