// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_blockArm_jsxConditional_yield.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, flip, element, Fragment } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
function* probe(input: Shape): Generator<unknown, unknown, Shape> {
  return <p>{flip() && ((t0: Shape) => { if (t0.kind === "Rect") { const { /*bind*/w, h } = t0; const /*bind2*/area = note("area", /*use*/w * h); if (/*use2*/area > 10) { return note("large", area); } return note("small", area); } return note("other", 0); })((yield /*operand*/input))}</p>;
}
