// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_wildcard_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, report } from "./harness.js";
type Token = { kind: "Num"; value: number } | { kind: "Neg"; value: number } | { kind: "Word"; text: string } | { kind: "End" };
const Token = {
  Num: (value: number): Token => ({ kind: "Num" as const, value }),
  Neg: (value: number): Token => ({ kind: "Neg" as const, value }),
  Word: (text: string): Token => ({ kind: "Word" as const, text }),
  End: { kind: "End" } as const,
};
const inputs: Token[] = [Token.Num(4), Token.Neg(-3), Token.Word("hi"), Token.End];
let input: Token = inputs[0]!;
const top0 = ((t0: Token) => { if (t0.kind === "Word") { const { /*bind*/text } = t0; return note("word", /*use*/text./*member*/length); } return note("other", -1); })(await later(/*operand*/input));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((t1: Token) => { if (t1.kind === "Word") { const { text } = t1; return note("word", text.length); } return note("other", -1); })(await later(input));
report("topLevel", input, text(top1));
input = inputs[2]!;
const top2 = ((t2: Token) => { if (t2.kind === "Word") { const { text } = t2; return note("word", text.length); } return note("other", -1); })(await later(input));
report("topLevel", input, text(top2));
input = inputs[3]!;
const top3 = ((t3: Token) => { if (t3.kind === "Word") { const { text } = t3; return note("word", text.length); } return note("other", -1); })(await later(input));
report("topLevel", input, text(top3));
