// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_tuple_topLevel_using.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, resource, report } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
type Speed = { kind: "Fast" } | { kind: "Slow" };
const Speed = {
  Fast: { kind: "Fast" } as const,
  Slow: { kind: "Slow" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
let input: Shape = inputs[0]!;
using res = resource("res");
const top0 = ((t0: Shape, t1: Speed) => { if (t0.kind === "Circle" && t1.kind === "Fast") { const { /*bind*/r } = t0; return note("fast circle", /*use*/r); } if (t0.kind === "Rect") { const { /*bind2*/w } = t0; return note("rect", /*use2*/w); } if (t1.kind === "Slow") return note("slow", 0); return note("rest", -1); })(note("operand", /*operand*/input), note<Speed>("second", Speed./*member*/Fast));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((t2: Shape, t3: Speed) => { if (t2.kind === "Circle" && t3.kind === "Fast") { const { r } = t2; return note("fast circle", r); } if (t2.kind === "Rect") { const { w } = t2; return note("rect", w); } if (t3.kind === "Slow") return note("slow", 0); return note("rest", -1); })(note("operand", input), note<Speed>("second", Speed.Fast));
report("topLevel", input, text(top1));
input = inputs[2]!;
const top2 = ((t4: Shape, t5: Speed) => { if (t4.kind === "Circle" && t5.kind === "Fast") { const { r } = t4; return note("fast circle", r); } if (t4.kind === "Rect") { const { w } = t4; return note("rect", w); } if (t5.kind === "Slow") return note("slow", 0); return note("rest", -1); })(note("operand", input), note<Speed>("second", Speed.Fast));
report("topLevel", input, text(top2));
