// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_blockArm_callArgument_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, box } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
function probe(input: Shape) {
  return pack(note("a", 1), ((t0: Shape) => { if (t0.kind === "Rect") { const { /*bind*/w, h } = t0; const /*bind2*/area = note("area", /*use*/w * h); if (/*use2*/area > 10) { return note("large", area); } return note("small", area); } return note("other", 0); })(box(/*operand*/input)?.inner.value!), note("c", 3));
}
