// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_booleanLiterals_jsxSpreadAttribute_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, unexpected, risky, element, Fragment } from "./harness.js";
let t0: any;
const inputs: boolean[] = [true, false];
function probe(input: boolean) {
  try {
    return <div {...{ value: (t0 = risky(/*operand*/input), t0 === true ? note("yes", 1) : t0 === false ? /*call*/note(/*arg*/"no", 0) : unexpected(t0)) }} />;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
