// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_wildcard_conditionalBranch_plain.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, flip } from "./harness.js";
type Token = { kind: "Num"; value: number } | { kind: "Neg"; value: number } | { kind: "Word"; text: string } | { kind: "End" };
const Token = {
  Num: (value: number): Token => ({ kind: "Num" as const, value }),
  Neg: (value: number): Token => ({ kind: "Neg" as const, value }),
  Word: (text: string): Token => ({ kind: "Word" as const, text }),
  End: { kind: "End" } as const,
};
const inputs: Token[] = [Token.Num(4), Token.Neg(-3), Token.Word("hi"), Token.End];
function probe(input: Token) {
  return flip() ? ((t0: Token) => { if (t0.kind === "Word") { const { /*bind*/text } = t0; return note("word", /*use*/text./*member*/length); } return note("other", -1); })(note("operand", /*operand*/input)) : note("else", "skipped");
}
