// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_nestedPattern_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, report } from "./harness.js";
type Maybe = { kind: "Some"; value: number } | { kind: "None" };
const Maybe = {
  Some: (value: number): Maybe => ({ kind: "Some" as const, value }),
  None: { kind: "None" } as const,
};
type Outcome = { kind: "Done"; value: Maybe } | { kind: "Failed"; error: string };
const Outcome = {
  Done: (value: Maybe): Outcome => ({ kind: "Done" as const, value }),
  Failed: (error: string): Outcome => ({ kind: "Failed" as const, error }),
};
const inputs: Outcome[] = [Outcome.Done(Maybe.Some(7)), Outcome.Done(Maybe.None), Outcome.Failed("lost")];
let input: Outcome = inputs[0]!;
const top0 = ((t0: Outcome) => { if (t0.kind === "Done" && t0.value.kind === "Some") { const /*bind*/v = t0.value.value; return note("some", /*use*/v); } if (t0.kind === "Done") { return note("none", 0); } { const { /*bind2*/error } = t0; return note("failed", /*use2*/error); } })(await later(/*operand*/input));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((t1: Outcome) => { if (t1.kind === "Done" && t1.value.kind === "Some") { const v = t1.value.value; return note("some", v); } if (t1.kind === "Done") { return note("none", 0); } { const { error } = t1; return note("failed", error); } })(await later(input));
report("topLevel", input, text(top1));
input = inputs[2]!;
const top2 = ((t2: Outcome) => { if (t2.kind === "Done" && t2.value.kind === "Some") { const v = t2.value.value; return note("some", v); } if (t2.kind === "Done") { return note("none", 0); } { const { error } = t2; return note("failed", error); } })(await later(input));
report("topLevel", input, text(top2));
