// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_isPatterns_topLevel_plain.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, report } from "./harness.js";
const inputs: unknown[] = [new RangeError("range"), new TypeError("type"), new Error("plain"), "text"];
let input: unknown = inputs[0]!;
const top0 = ((t0: unknown) => { if (t0 instanceof /*call*/RangeError) { const { /*bind*/message } = t0; return note("range", /*use*/message); } if (t0 instanceof TypeError || t0 instanceof SyntaxError) return note("type", 1); if (t0 instanceof Error) { const { /*field*/message: /*bind2*/detail } = t0; return note("error", /*use2*/detail); } return note("other", null); })(note("operand", /*operand*/input));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((t1: unknown) => { if (t1 instanceof RangeError) { const { message } = t1; return note("range", message); } if (t1 instanceof TypeError || t1 instanceof SyntaxError) return note("type", 1); if (t1 instanceof Error) { const { message: detail } = t1; return note("error", detail); } return note("other", null); })(note("operand", input));
report("topLevel", input, text(top1));
input = inputs[2]!;
const top2 = ((t2: unknown) => { if (t2 instanceof RangeError) { const { message } = t2; return note("range", message); } if (t2 instanceof TypeError || t2 instanceof SyntaxError) return note("type", 1); if (t2 instanceof Error) { const { message: detail } = t2; return note("error", detail); } return note("other", null); })(note("operand", input));
report("topLevel", input, text(top2));
input = inputs[3]!;
const top3 = ((t3: unknown) => { if (t3 instanceof RangeError) { const { message } = t3; return note("range", message); } if (t3 instanceof TypeError || t3 instanceof SyntaxError) return note("type", 1); if (t3 instanceof Error) { const { message: detail } = t3; return note("error", detail); } return note("other", null); })(note("operand", input));
report("topLevel", input, text(top3));
