// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_tuple_templateLiteral_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
type Speed = { kind: "Fast" } | { kind: "Slow" };
const Speed = {
  Fast: { kind: "Fast" } as const,
  Slow: { kind: "Slow" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
function probe(input: Shape) {
  try {
    return `<${note("left", "L")}|${((t0: Shape, t1: Speed) => { if (t0.kind === "Circle" && t1.kind === "Fast") { const { /*bind*/r } = t0; return note("fast circle", /*use*/r); } if (t0.kind === "Rect") { const { /*bind2*/w } = t0; return note("rect", /*use2*/w); } if (t1.kind === "Slow") return note("slow", 0); return note("rest", -1); })(note("operand", /*operand*/input), note<Speed>("second", Speed./*member*/Fast))}|${note("right", "R")}>`;
  } finally {
    note("finally", 0);
  }
}
