// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_booleanLiterals_jsxTernary_optionalChain.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, unexpected, flip, box, element, Fragment } from "./harness.js";
let t0: any;
const inputs: boolean[] = [true, false];
function probe(input: boolean) {
  return <p>{flip() ? (t0 = box(/*operand*/input)?.inner.value!, t0 === true ? note("yes", 1) : t0 === false ? /*call*/note(/*arg*/"no", 0) : unexpected(t0)) : <i>none</i>}</p>;
}
