// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_numberLiterals_callArgument_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack } from "./harness.js";
let t0: any;
const inputs: number[] = [200, 201, 404, 500, 7];
function probe(input: number) {
  try {
    return pack(note("a", 1), (t0 = note("operand", /*operand*/input), t0 === 200 || t0 === 201 ? note("success", true) : t0 === 404 ? note("missing", false) : t0 === 500 && /*call*/note(/*arg*/"guard", true) ? note("server", false) : note("other", null)), note("c", 3));
  } finally {
    note("finally", 0);
  }
}
