// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_booleanLiterals_callArgument_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, unexpected, pack, first } from "./harness.js";
let t0: any;
const inputs: boolean[] = [true, false];
function probe(input: boolean) {
  return pack(note("a", 1), (t0 = first(...[/*operand*/input]), t0 === true ? note("yes", 1) : t0 === false ? /*call*/note(/*arg*/"no", 0) : unexpected(t0)), note("c", 3));
}
