// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_stringLiterals_awaitOperand_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
let t0: any;
const inputs: string[] = ["north", "south", "east", "up"];
async function probe(input: string) {
  return await ((t0 = note("operand", /*operand*/input), t0 === "north" ? /*call*/note(/*arg*/"n", 1) : t0 === "south" || t0 === "east" ? note("se", 2) : note("other", 0)));
}
