// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_stringLiterals_jsxTernary_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, flip, risky, element, Fragment } from "./harness.js";
let t0: any;
const inputs: string[] = ["north", "south", "east", "up"];
function probe(input: string) {
  try {
    return <p>{flip() ? (t0 = risky(/*operand*/input), t0 === "north" ? /*call*/note(/*arg*/"n", 1) : t0 === "south" || t0 === "east" ? note("se", 2) : note("other", 0)) : <i>none</i>}</p>;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
