// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_nestedMatch_jsxChild_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, later, element, Fragment } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
async function probe(input: Shape) {
  return <p>{((t1: number) => { if (t1 === 0) return note("zero", "none"); return ((t2: Shape) => { if (t2.kind === "Point") return note("point", "some"); return note("other", "?"); })(note("again", Shape./*member*/Point)); })(((t0: Shape) => { if (t0.kind === "Point") return note("inner point", 0); if (t0.kind === "Circle") { const { /*bind*/r } = t0; return note("inner circle", /*use*/r); } { const { w } = t0; return note("inner rect", w); } })(await later(/*operand*/input)))}</p>;
}
