// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_numberLiterals_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, report } from "./harness.js";
let t0: any, t1: any, t2: any, t3: any, t4: any;
const inputs: number[] = [200, 201, 404, 500, 7];
let input: number = inputs[0]!;
const top0 = (t0 = await later(/*operand*/input), t0 === 200 || t0 === 201 ? note("success", true) : t0 === 404 ? note("missing", false) : t0 === 500 && /*call*/note(/*arg*/"guard", true) ? note("server", false) : note("other", null));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = (t1 = await later(input), t1 === 200 || t1 === 201 ? note("success", true) : t1 === 404 ? note("missing", false) : t1 === 500 && note("guard", true) ? note("server", false) : note("other", null));
report("topLevel", input, text(top1));
input = inputs[2]!;
const top2 = (t2 = await later(input), t2 === 200 || t2 === 201 ? note("success", true) : t2 === 404 ? note("missing", false) : t2 === 500 && note("guard", true) ? note("server", false) : note("other", null));
report("topLevel", input, text(top2));
input = inputs[3]!;
const top3 = (t3 = await later(input), t3 === 200 || t3 === 201 ? note("success", true) : t3 === 404 ? note("missing", false) : t3 === 500 && note("guard", true) ? note("server", false) : note("other", null));
report("topLevel", input, text(top3));
input = inputs[4]!;
const top4 = (t4 = await later(input), t4 === 200 || t4 === 201 ? note("success", true) : t4 === 404 ? note("missing", false) : t4 === 500 && note("guard", true) ? note("server", false) : note("other", null));
report("topLevel", input, text(top4));
