// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_booleanLiterals_arrowBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, unexpected, later } from "./harness.js";
let t0: any;
const inputs: boolean[] = [true, false];
function probe(input: boolean) {
  const inner = async (input: boolean) => (t0 = await later(/*operand*/input), t0 === true ? note("yes", 1) : t0 === false ? /*call*/note(/*arg*/"no", 0) : unexpected(t0));
  return inner(input);
}
