// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_booleanLiterals_jsxChild_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, unexpected, later, element, Fragment } from "./harness.js";
let t0: any;
const inputs: boolean[] = [true, false];
async function probe(input: boolean) {
  return <p>{(t0 = await later(/*operand*/input), t0 === true ? note("yes", 1) : t0 === false ? /*call*/note(/*arg*/"no", 0) : unexpected(t0))}</p>;
}
