// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_handWrittenUnion_logicalAnd_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, risky } from "./harness.js";
type Event = { kind: "Click"; x: number } | { kind: "Key"; key: string };
const inputs: Event[] = [{ kind: "Click", x: 3 }, { kind: "Key", key: "k" }];
function probe(input: Event) {
  try {
    return flip() && ((t0: Event) => { if (t0.kind === "Click") { const { /*bind*/x } = t0; return note("click", /*use*/x); } { const { /*bind2*/key } = t0; return note("key", /*use2*/key); } })(risky(/*operand*/input));
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
