// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_fieldAlias_templateLiteral_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
function probe(input: Shape) {
  return `<${note("left", "L")}|${((t0: Shape) => { if (t0.kind === "Rect") { const { /*field*/h: /*bind*/tall, w: wide } = t0; return note("rect", [wide, /*use*/tall]); } if (t0.kind === "Circle") { const { r: /*bind2*/radius } = t0; return note("circle", /*use2*/radius); } return note("point", null); })(box(/*operand*/input)?.inner.value!)}|${note("right", "R")}>`;
}
