// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_booleanLiterals_jsxNested_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, element, Fragment } from "./harness.js";
let t0: any;
const inputs: boolean[] = [true, false];
function probe(input: boolean) {
  try {
    return <ul><li>{note("first", 1)}</li><li>{(t0 = note("operand", /*operand*/input), t0 === true ? note("yes", 1) : /*call*/note(/*arg*/"no", 0))}</li></ul>;
  } finally {
    note("finally", 0);
  }
}
