// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_nestedMatch_topLevel_using.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, resource, report } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
let input: Shape = inputs[0]!;
using res = resource("res");
const top0 = ((t1: number) => { if (t1 === 0) return note("zero", "none"); return ((t2: Shape) => { if (t2.kind === "Point") return note("point", "some"); return note("other", "?"); })(note("again", Shape./*member*/Point)); })(((t0: Shape) => { if (t0.kind === "Point") return note("inner point", 0); if (t0.kind === "Circle") { const { /*bind*/r } = t0; return note("inner circle", /*use*/r); } { const { w } = t0; return note("inner rect", w); } })(note("operand", /*operand*/input)));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((t4: number) => { if (t4 === 0) return note("zero", "none"); return ((t5: Shape) => { if (t5.kind === "Point") return note("point", "some"); return note("other", "?"); })(note("again", Shape.Point)); })(((t3: Shape) => { if (t3.kind === "Point") return note("inner point", 0); if (t3.kind === "Circle") { const { r } = t3; return note("inner circle", r); } { const { w } = t3; return note("inner rect", w); } })(note("operand", input)));
report("topLevel", input, text(top1));
input = inputs[2]!;
const top2 = ((t7: number) => { if (t7 === 0) return note("zero", "none"); return ((t8: Shape) => { if (t8.kind === "Point") return note("point", "some"); return note("other", "?"); })(note("again", Shape.Point)); })(((t6: Shape) => { if (t6.kind === "Point") return note("inner point", 0); if (t6.kind === "Circle") { const { r } = t6; return note("inner circle", r); } { const { w } = t6; return note("inner rect", w); } })(note("operand", input)));
report("topLevel", input, text(top2));
