// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_guards_loopBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Circle(1), Shape.Circle(5), Shape.Rect(4, 2), Shape.Rect(1, 3), Shape.Point];
function probe(input: Shape) {
  try {
    const collected: unknown[] = [];
    for (let round = 0; round < 2; round++) {
      collected.push(((t0: Shape) => { if (t0.kind === "Circle") { const { /*bind*/r } = t0; if (note("guard big", /*use*/r > 2)) return note("big", /*use2*/r); } if (t0.kind === "Circle") { const { r } = t0; return note("small", r); } if (t0.kind === "Rect") { const { w, h } = t0; if (note("guard wide", w > h)) return note("wide", w); } if (t0.kind === "Rect") { const { w, h } = t0; return note("tall", h); } return note("point", 0); })(risky(/*operand*/input)));
    }
    return collected;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
