// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_jsxArms_jsxAttribute_plain.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, element, Fragment } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
function probe(input: Shape) {
  return <div /*attrHost*/data-value={((t0: Shape) => { if (t0.kind === "Circle") { const { /*bind*/r } = t0; return <b>{note("circle", /*use*/r)}</b>; } if (t0.kind === "Rect") { const { /*bind2*/w, h } = t0; return <i /*attr*/title={String(/*use2*/w)}>{h}</i>; } return <>point</>; })(note("operand", /*operand*/input))} />;
}
