// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_isPatterns_jsxFragment_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, first, element, Fragment } from "./harness.js";
const inputs: unknown[] = [new RangeError("range"), new TypeError("type"), new Error("plain"), "text"];
function probe(input: unknown) {
  return <>{note("before", "[")}{((t0: unknown) => { if (t0 instanceof /*call*/RangeError) { const { /*bind*/message } = t0; return note("range", /*use*/message); } if (t0 instanceof TypeError || t0 instanceof SyntaxError) return note("type", 1); if (t0 instanceof Error) { const { /*field*/message: /*bind2*/detail } = t0; return note("error", /*use2*/detail); } return note("other", null); })(first(...[/*operand*/input]))}{note("after", "]")}</>;
}
