// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_tagBindings_callArgument_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, first } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
function probe(input: Shape) {
  return pack(note("a", 1), ((t0: Shape) => { if (t0.kind === "Circle") { const { /*bind*/r } = t0; return note("circle", /*use*/r * 2); } if (t0.kind === "Rect") { const { w, /*bind2*/h } = t0; return /*call*/note(/*arg*/"rect", w * /*use2*/h); } return note("point", 0); })(first(...[/*operand*/input])), note("c", 3));
}
