// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_nestedPattern_callArgument_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, risky } from "./harness.js";
type Maybe = { kind: "Some"; value: number } | { kind: "None" };
const Maybe = {
  Some: (value: number): Maybe => ({ kind: "Some" as const, value }),
  None: { kind: "None" } as const,
};
type Outcome = { kind: "Done"; value: Maybe } | { kind: "Failed"; error: string };
const Outcome = {
  Done: (value: Maybe): Outcome => ({ kind: "Done" as const, value }),
  Failed: (error: string): Outcome => ({ kind: "Failed" as const, error }),
};
const inputs: Outcome[] = [Outcome.Done(Maybe.Some(7)), Outcome.Done(Maybe.None), Outcome.Failed("lost")];
function probe(input: Outcome) {
  try {
    return pack(note("a", 1), ((t0: Outcome) => { if (t0.kind === "Done" && t0.value.kind === "Some") { const /*bind*/v = t0.value.value; return note("some", /*use*/v); } if (t0.kind === "Done") { return note("none", 0); } { const { /*bind2*/error } = t0; return note("failed", /*use2*/error); } })(risky(/*operand*/input)), note("c", 3));
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
