// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_booleanLiterals_awaitOperand_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, unexpected, box } from "./harness.js";
let t0: any;
const inputs: boolean[] = [true, false];
async function probe(input: boolean) {
  return await ((t0 = box(/*operand*/input)?.inner.value!, t0 === true ? note("yes", 1) : t0 === false ? /*call*/note(/*arg*/"no", 0) : unexpected(t0)));
}
