// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_blockArm_topLevel_spread.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, first, report } from "./harness.js";
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number } | { kind: "Point" };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
  Point: { kind: "Point" } as const,
};
const inputs: Shape[] = [Shape.Circle(2), Shape.Rect(3, 4), Shape.Point];
let input: Shape = inputs[0]!;
const top0 = ((t0: Shape) => { if (t0.kind === "Rect") { const { /*bind*/w, h } = t0; const /*bind2*/area = note("area", /*use*/w * h); if (/*use2*/area > 10) { return note("large", area); } return note("small", area); } return note("other", 0); })(first(...[/*operand*/input]));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((t1: Shape) => { if (t1.kind === "Rect") { const { w, h } = t1; const area = note("area", w * h); if (area > 10) { return note("large", area); } return note("small", area); } return note("other", 0); })(first(...[input]));
report("topLevel", input, text(top1));
input = inputs[2]!;
const top2 = ((t2: Shape) => { if (t2.kind === "Rect") { const { w, h } = t2; const area = note("area", w * h); if (area > 10) { return note("large", area); } return note("small", area); } return note("other", 0); })(first(...[input]));
report("topLevel", input, text(top2));
