// Generated by scripts/generate-cases from tests/matrix/match.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of match_isPatterns_ifLetBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, read } from "./harness.js";
const inputs: unknown[] = [new RangeError("range"), new TypeError("type"), new Error("plain"), "text"];
async function probe(input: unknown) {
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, ((t0: unknown) => { if (t0 instanceof /*call*/RangeError) { const { /*bind*/message } = t0; return note("range", /*use*/message); } if (t0 instanceof TypeError || t0 instanceof SyntaxError) return note("type", 1); if (t0 instanceof Error) { const { /*field*/message: /*bind2*/detail } = t0; return note("error", /*use2*/detail); } return note("other", null); })(await later(/*operand*/input))];
  }
  return null;
}
