// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_binaryOperand_jsxNested_using.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, resource, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [3, -2];
function probe(input: number) {
  try {
    using res = resource("res");
    return ok(<ul><li>{note("first", 1)}</li><li>{(unwrap(/*call*/read(note("operand", /*operand*/input))) * 10)}</li></ul>);
  } catch (error) {
    return caught(error);
  }
}
