// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_parenthesized_jsxAttribute_optionalChain.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, flip, box, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [6, -6];
function probe(input: number) {
  try {
    return ok(<div /*attrHost*/data-value={unwrap(/*call*/flip() ? read(box(/*operand*/input)?.inner.value!) : read(/*arg*/note("fallback", -9)))} />);
  } catch (error) {
    return caught(error);
  }
}
