// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_binaryOperand_callArgument_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, risky, ok, read, Propagate, unwrap, caught } from "./harness.js";
const inputs: number[] = [3, -2];
function probe(input: number) {
  try {
    try {
      return ok(pack(note("a", 1), (unwrap(/*call*/read(risky(/*operand*/input))) * 10), note("c", 3)));
    } catch (error) {
      if (error instanceof Propagate) throw error;
      return ok(note("caught", (error as Error).message));
    }
  } catch (error) {
    return caught(error);
  }
}
