// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_siblings_callArgument_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, box, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  try {
    return ok(pack(note("a", 1), (unwrap(read(box(/*operand*/input)?.inner.value!)) + unwrap(/*call*/read(/*arg*/note("second", 5)))), note("c", 3)));
  } catch (error) {
    return caught(error);
  }
}
