// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_siblings_conditionalBranch_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, box, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  try {
    return ok(flip() ? (unwrap(read(box(/*operand*/input)?.inner.value!)) + unwrap(/*call*/read(/*arg*/note("second", 5)))) : note("else", "skipped"));
  } catch (error) {
    return caught(error);
  }
}
