// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_binaryOperand_jsxComponentProp_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, ok, read, unwrap, caught, Show, element, Fragment } from "./harness.js";
const inputs: number[] = [3, -2];
function probe(input: number) {
  try {
    try {
      return ok(<Show /*attrHost*/value={(unwrap(/*call*/read(note("operand", /*operand*/input))) * 10)} />);
    } finally {
      note("finally", 0);
    }
  } catch (error) {
    return caught(error);
  }
}
