// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_binaryOperand_loopBody_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [3, -2];
function probe(input: number) {
  try {
    const collected: unknown[] = [];
    for (let round = 0; round < 2; round++) {
      collected.push((unwrap(/*call*/read(box(/*operand*/input)?.inner.value!)) * 10));
    }
    return ok(collected);
  } catch (error) {
    return caught(error);
  }
}
