// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_operand_jsxSpreadAttribute_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, risky, ok, read, Propagate, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    try {
      return ok(<div {...{ value: unwrap(/*call*/read(/*arg*/risky(/*operand*/input))) }} />);
    } catch (error) {
      if (error instanceof Propagate) throw error;
      return ok(note("caught", (error as Error).message));
    }
  } catch (error) {
    return caught(error);
  }
}
