// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_binaryOperand_conditionalBranch_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, flip, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [3, -2];
async function probe(input: number) {
  try {
    return ok(flip() ? (unwrap(/*call*/read(await later(/*operand*/input))) * 10) : note("else", "skipped"));
  } catch (error) {
    return caught(error);
  }
}
