// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_binaryOperand_logicalAnd_spread.tt; it shares the case's other units.
// @filename: main.ts
import { flip, first, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [3, -2];
function probe(input: number) {
  try {
    return ok(flip() && (unwrap(/*call*/read(first(...[/*operand*/input]))) * 10));
  } catch (error) {
    return caught(error);
  }
}
