// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_binaryOperand_jsxAttribute_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { later, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [3, -2];
async function probe(input: number) {
  try {
    return ok(<div /*attrHost*/data-value={(unwrap(/*call*/read(await later(/*operand*/input))) * 10)} />);
  } catch (error) {
    return caught(error);
  }
}
