// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_matchOperand_objectProperty_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, ok, read, Propagate, unwrap, caught } from "./harness.js";
const inputs: number[] = [1, 2, -3];
function probe(input: number) {
  try {
    try {
      return ok({ a: note("a", 1), value: unwrap(((t0: number) => (t0 === 1 ? /*call*/read(/*arg*/note("one", 10)) : read(note("other", -10))))(risky(/*operand*/input))), c: note("c", 3) });
    } catch (error) {
      if (error instanceof Propagate) throw error;
      return ok(note("caught", (error as Error).message));
    }
  } catch (error) {
    return caught(error);
  }
}
