// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_matchOperand_loopBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [1, 2, -3];
async function probe(input: number) {
  try {
    const collected: unknown[] = [];
    for (let round = 0; round < 2; round++) {
      collected.push(unwrap(((t0: number) => (t0 === 1 ? /*call*/read(/*arg*/note("one", 10)) : read(note("other", -10))))(await later(/*operand*/input))));
    }
    return ok(collected);
  } catch (error) {
    return caught(error);
  }
}
