// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_binaryOperand_jsxSpreadAttribute_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { first, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [3, -2];
function probe(input: number) {
  try {
    return ok(<div {...{ value: (unwrap(/*call*/read(first(...[/*operand*/input]))) * 10) }} />);
  } catch (error) {
    return caught(error);
  }
}
