// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_parenthesized_templateLiteral_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [6, -6];
function probe(input: number) {
  try {
    return ok(`<${note("left", "L")}|${unwrap(/*call*/flip() ? read(note("operand", /*operand*/input)) : read(/*arg*/note("fallback", -9)))}|${note("right", "R")}>`);
  } catch (error) {
    return caught(error);
  }
}
