// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_parenthesized_jsxConditional_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, later, flip, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [6, -6];
async function probe(input: number) {
  try {
    return ok(<p>{flip() && unwrap(/*call*/flip() ? read(await later(/*operand*/input)) : read(/*arg*/note("fallback", -9)))}</p>);
  } catch (error) {
    return caught(error);
  }
}
