// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_memberOfValue_jsxNested_optionalChain.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, box, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [1.5, -1];
function probe(input: number) {
  try {
    return ok(<ul><li>{note("first", 1)}</li><li>{unwrap(read(box(/*operand*/input)?.inner.value!))./*member*/toFixed(/*arg*/2)}</li></ul>);
  } catch (error) {
    return caught(error);
  }
}
