// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_operand_awaitOperand_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
async function probe(input: number) {
  try {
    return ok(await (unwrap(/*call*/read(/*arg*/box(/*operand*/input)?.inner.value!))));
  } catch (error) {
    return caught(error);
  }
}
