// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_parenthesized_objectProperty_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [6, -6];
function probe(input: number) {
  try {
    return ok({ a: note("a", 1), value: unwrap(/*call*/flip() ? read(note("operand", /*operand*/input)) : read(/*arg*/note("fallback", -9))), c: note("c", 3) });
  } catch (error) {
    return caught(error);
  }
}
