// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_siblings_returnOperand_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  try {
    return ok((unwrap(read(first(...[/*operand*/input]))) + unwrap(/*call*/read(/*arg*/note("second", 5)))));
  } catch (error) {
    return caught(error);
  }
}
