// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_matchOperand_jsxComponentProp_optionalChain.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, box, ok, read, unwrap, caught, Show, element, Fragment } from "./harness.js";
const inputs: number[] = [1, 2, -3];
function probe(input: number) {
  try {
    return ok(<Show /*attrHost*/value={unwrap(((t0: number) => (t0 === 1 ? /*call*/read(/*arg*/note("one", 10)) : read(note("other", -10))))(box(/*operand*/input)?.inner.value!))} />);
  } catch (error) {
    return caught(error);
  }
}
