// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_siblings_ifLetBody_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  try {
    using res = resource("res");
    const head = read(note("head", 1));
    if (head.kind === "Ok") {
      const n = head.value;
      return ok([n, (unwrap(read(note("operand", /*operand*/input))) + unwrap(/*call*/read(/*arg*/note("second", 5))))]);
    }
    return ok(null);
  } catch (error) {
    return caught(error);
  }
}
