// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_operand_jsxComponentProp_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { later, ok, read, unwrap, caught, Show, element, Fragment } from "./harness.js";
const inputs: number[] = [2, -1];
async function probe(input: number) {
  try {
    return ok(<Show /*attrHost*/value={unwrap(/*call*/read(/*arg*/await later(/*operand*/input)))} />);
  } catch (error) {
    return caught(error);
  }
}
