// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_siblings_jsxSpreadAttribute_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  try {
    try {
      return ok(<div {...{ value: (unwrap(read(note("operand", /*operand*/input))) + unwrap(/*call*/read(/*arg*/note("second", 5)))) }} />);
    } finally {
      note("finally", 0);
    }
  } catch (error) {
    return caught(error);
  }
}
