// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_parenthesized_jsxComponentProp_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, flip, risky, ok, read, Propagate, unwrap, caught, Show, element, Fragment } from "./harness.js";
const inputs: number[] = [6, -6];
function probe(input: number) {
  try {
    try {
      return ok(<Show /*attrHost*/value={unwrap(/*call*/flip() ? read(risky(/*operand*/input)) : read(/*arg*/note("fallback", -9)))} />);
    } catch (error) {
      if (error instanceof Propagate) throw error;
      return ok(note("caught", (error as Error).message));
    }
  } catch (error) {
    return caught(error);
  }
}
