// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_memberOfValue_jsxAttribute_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { first, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [1.5, -1];
function probe(input: number) {
  try {
    return ok(<div /*attrHost*/data-value={unwrap(read(first(...[/*operand*/input])))./*member*/toFixed(/*arg*/2)} />);
  } catch (error) {
    return caught(error);
  }
}
