// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_binaryOperand_objectProperty_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [3, -2];
function probe(input: number) {
  try {
    using res = resource("res");
    return ok({ a: note("a", 1), value: (unwrap(/*call*/read(note("operand", /*operand*/input))) * 10), c: note("c", 3) });
  } catch (error) {
    return caught(error);
  }
}
