// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_memberOfValue_jsxConditional_using.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, flip, resource, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [1.5, -1];
function probe(input: number) {
  try {
    using res = resource("res");
    return ok(<p>{flip() && unwrap(read(note("operand", /*operand*/input)))./*member*/toFixed(/*arg*/2)}</p>);
  } catch (error) {
    return caught(error);
  }
}
