// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_operand_jsxFragment_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, first, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    return ok(<>{note("before", "[")}{unwrap(/*call*/read(/*arg*/first(...[/*operand*/input])))}{note("after", "]")}</>);
  } catch (error) {
    return caught(error);
  }
}
