// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_binaryOperand_loopBody_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [3, -2];
function probe(input: number) {
  try {
    try {
      const collected: unknown[] = [];
      for (let round = 0; round < 2; round++) {
        collected.push((unwrap(/*call*/read(note("operand", /*operand*/input))) * 10));
      }
      return ok(collected);
    } finally {
      note("finally", 0);
    }
  } catch (error) {
    return caught(error);
  }
}
