// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_memberOfValue_jsxFragment_plain.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [1.5, -1];
function probe(input: number) {
  try {
    return ok(<>{note("before", "[")}{unwrap(read(note("operand", /*operand*/input)))./*member*/toFixed(/*arg*/2)}{note("after", "]")}</>);
  } catch (error) {
    return caught(error);
  }
}
