// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_operand_jsxNested_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, later, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [2, -1];
async function probe(input: number) {
  try {
    return ok(<ul><li>{note("first", 1)}</li><li>{unwrap(/*call*/read(/*arg*/await later(/*operand*/input)))}</li></ul>);
  } catch (error) {
    return caught(error);
  }
}
