// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_binaryOperand_templateLiteral_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [3, -2];
function probe(input: number) {
  try {
    return ok(`<${note("left", "L")}|${(unwrap(/*call*/read(box(/*operand*/input)?.inner.value!)) * 10)}|${note("right", "R")}>`);
  } catch (error) {
    return caught(error);
  }
}
