// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_memberOfValue_awaitOperand_await.tt; it shares the case's other units.
// @filename: main.ts
import { later, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [1.5, -1];
async function probe(input: number) {
  try {
    return ok(await (unwrap(read(await later(/*operand*/input)))./*member*/toFixed(/*arg*/2)));
  } catch (error) {
    return caught(error);
  }
}
