// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_parenthesized_jsxFragment_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, flip, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [6, -6];
function probe(input: number) {
  try {
    try {
      return ok(<>{note("before", "[")}{unwrap(/*call*/flip() ? read(note("operand", /*operand*/input)) : read(/*arg*/note("fallback", -9)))}{note("after", "]")}</>);
    } finally {
      note("finally", 0);
    }
  } catch (error) {
    return caught(error);
  }
}
