// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_matchOperand_awaitOperand_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [1, 2, -3];
async function probe(input: number) {
  try {
    try {
      return ok(await (unwrap(((t0: number) => (t0 === 1 ? /*call*/read(/*arg*/note("one", 10)) : read(note("other", -10))))(note("operand", /*operand*/input)))));
    } finally {
      note("finally", 0);
    }
  } catch (error) {
    return caught(error);
  }
}
