// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_siblings_jsxChild_optionalChain.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, box, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  try {
    return ok(<p>{(unwrap(read(box(/*operand*/input)?.inner.value!)) + unwrap(/*call*/read(/*arg*/note("second", 5))))}</p>);
  } catch (error) {
    return caught(error);
  }
}
