// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_siblings_objectProperty_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  try {
    return ok({ a: note("a", 1), value: (unwrap(read(box(/*operand*/input)?.inner.value!)) + unwrap(/*call*/read(/*arg*/note("second", 5)))), c: note("c", 3) });
  } catch (error) {
    return caught(error);
  }
}
