// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_operand_awaitOperand_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
async function probe(input: number) {
  try {
    using res = resource("res");
    return ok(await (unwrap(/*call*/read(/*arg*/note("operand", /*operand*/input)))));
  } catch (error) {
    return caught(error);
  }
}
