// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_operand_jsxNested_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    try {
      return ok(<ul><li>{note("first", 1)}</li><li>{unwrap(/*call*/read(/*arg*/note("operand", /*operand*/input)))}</li></ul>);
    } finally {
      note("finally", 0);
    }
  } catch (error) {
    return caught(error);
  }
}
