// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_siblings_method_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  class Holder {
    tag = "holder";
    read(input: number) {
      try {
        note("this", this.tag);
        return ok((unwrap(read(note("operand", /*operand*/input))) + unwrap(/*call*/read(/*arg*/note("second", 5)))));
      } catch (error) {
        return caught(error);
      }
    }
  }
  return new Holder().read(input);
}
