// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_matchOperand_jsxFragment_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, later, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [1, 2, -3];
async function probe(input: number) {
  try {
    return ok(<>{note("before", "[")}{unwrap(((t0: number) => (t0 === 1 ? /*call*/read(/*arg*/note("one", 10)) : read(note("other", -10))))(await later(/*operand*/input)))}{note("after", "]")}</>);
  } catch (error) {
    return caught(error);
  }
}
