// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_operand_matchArm_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, box, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    return ok((flip() ? unwrap(/*call*/read(/*arg*/box(/*operand*/input)?.inner.value!)) : note("other arm", 0)));
  } catch (error) {
    return caught(error);
  }
}
