// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_siblings_jsxNested_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, risky, ok, read, Propagate, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  try {
    try {
      return ok(<ul><li>{note("first", 1)}</li><li>{(unwrap(read(risky(/*operand*/input))) + unwrap(/*call*/read(/*arg*/note("second", 5))))}</li></ul>);
    } catch (error) {
      if (error instanceof Propagate) throw error;
      return ok(note("caught", (error as Error).message));
    }
  } catch (error) {
    return caught(error);
  }
}
