// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_matchOperand_jsxSpreadAttribute_plain.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [1, 2, -3];
function probe(input: number) {
  try {
    return ok(<div {...{ value: unwrap(((t0: number) => (t0 === 1 ? /*call*/read(/*arg*/note("one", 10)) : read(note("other", -10))))(note("operand", /*operand*/input))) }} />);
  } catch (error) {
    return caught(error);
  }
}
