// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_siblings_loopBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, ok, read, Propagate, unwrap, caught } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  try {
    try {
      const collected: unknown[] = [];
      for (let round = 0; round < 2; round++) {
        collected.push((unwrap(read(risky(/*operand*/input))) + unwrap(/*call*/read(/*arg*/note("second", 5)))));
      }
      return ok(collected);
    } catch (error) {
      if (error instanceof Propagate) throw error;
      return ok(note("caught", (error as Error).message));
    }
  } catch (error) {
    return caught(error);
  }
}
