// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_operand_objectProperty_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -1];
async function probe(input: number) {
  try {
    return ok({ a: note("a", 1), value: unwrap(/*call*/read(/*arg*/await later(/*operand*/input))), c: note("c", 3) });
  } catch (error) {
    return caught(error);
  }
}
