// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_memberOfValue_jsxSpreadAttribute_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { later, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [1.5, -1];
async function probe(input: number) {
  try {
    return ok(<div {...{ value: unwrap(read(await later(/*operand*/input)))./*member*/toFixed(/*arg*/2) }} />);
  } catch (error) {
    return caught(error);
  }
}
