// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_parenthesized_nullish_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, resource, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [6, -6];
function probe(input: number) {
  try {
    using res = resource("res");
    return ok((flip() ? null : note("left", "set")) ?? unwrap(/*call*/flip() ? read(note("operand", /*operand*/input)) : read(/*arg*/note("fallback", -9))));
  } catch (error) {
    return caught(error);
  }
}
