// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_siblings_jsxTernary_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, later, flip, ok, read, unwrap, caught, element, Fragment } from "./harness.js";
const inputs: number[] = [4, -4];
async function probe(input: number) {
  try {
    return ok(<p>{flip() ? (unwrap(read(await later(/*operand*/input))) + unwrap(/*call*/read(/*arg*/note("second", 5)))) : <i>none</i>}</p>);
  } catch (error) {
    return caught(error);
  }
}
