// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_memberOfValue_method_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, ok, read, Propagate, unwrap, caught } from "./harness.js";
const inputs: number[] = [1.5, -1];
function probe(input: number) {
  try {
    class Holder {
      tag = "holder";
      read(input: number) {
        try {
          note("this", this.tag);
          return ok(unwrap(read(risky(/*operand*/input)))./*member*/toFixed(/*arg*/2));
        } catch (error) {
          return caught(error);
        }
      }
    }
    return new Holder().read(input);
  } catch (error) {
    if (error instanceof Propagate) throw error;
    return ok(note("caught", (error as Error).message));
  }
}
