// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_memberOfValue_declarationInitializer_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [1.5, -1];
function probe(input: number) {
  try {
    const value = unwrap(read(box(/*operand*/input)?.inner.value!))./*member*/toFixed(/*arg*/2);
    return ok(value);
  } catch (error) {
    return caught(error);
  }
}
