// Generated by scripts/generate-cases from tests/matrix/try.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of try_memberOfValue_templateLiteral_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [1.5, -1];
function probe(input: number) {
  try {
    return ok(`<${note("left", "L")}|${unwrap(read(first(...[/*operand*/input])))./*member*/toFixed(/*arg*/2)}|${note("right", "R")}>`);
  } catch (error) {
    return caught(error);
  }
}
