export default {
  construct: "flow",
  kind: "value",
  lowPrecedence: true,
  skip: ["templateLiteral"],
  forms: [
    {
      id: "twoSteps",
      title: "two steps composed, the second built from the operand",
      In: "number",
      inputs: "[2, 5]",
      tt: (x) => `flow |> /*@call*/double |> /*@call2*/adder(/*@arg*/${x})`,
      ts: (x) => `((second: (n: number) => number) => (v: number) => second(/*@call*/double(v)))(/*@call2*/adder(/*@arg*/${x}))`,
    },
    {
      id: "firstStepExpression",
      title: "a first step that is a call, evaluated at composition",
      In: "number",
      inputs: "[3, -4]",
      tt: (x) => `flow |> /*@call*/adder(/*@arg*/${x}) |> /*@call2*/String`,
      ts: (x) => `((head: (n: number) => number) => (v: number) => /*@call2*/String(head(v)))(/*@call*/adder(/*@arg*/${x}))`,
    },
    {
      id: "oneStep",
      title: "a single step, which is the step itself",
      In: "number",
      inputs: "[7, 1]",
      tt: (x) => `flow |> /*@call*/adder(/*@arg*/${x})`,
      ts: (x) => `/*@call*/adder(/*@arg*/${x})`,
    },
    {
      id: "postfixLater",
      title: "a later postfix step",
      In: "number",
      inputs: "[1.5, 2]",
      tt: (x) => `flow |> adder(${x}) |> ./*@member*/toFixed(/*@arg*/1)`,
      ts: (x) => `((head: (n: number) => number) => (v: number) => head(v)./*@member*/toFixed(/*@arg*/1))(adder(${x}))`,
    },
    {
      id: "memberLater",
      title: "a later member step whose receiver is read at composition",
      In: "number",
      inputs: "[2, 3]",
      tt: (x) => `flow |> adder(${x}) |> note("receiver", /*@use*/tools)./*@member*/twice`,
      ts: (x) =>
        `((head: (n: number) => number, receiver: typeof tools) => (v: number) => receiver./*@member*/twice(head(v)))(adder(${x}), note("receiver", /*@use*/tools))`,
    },
    {
      id: "optionalLater",
      title: "a later optional-chain step whose receiver is read at composition",
      In: "number",
      inputs: "[4, 6, 8]",
      tt: (x) => `flow |> adder(${x}) |> /*@call*/maybe(/*@arg*/flip())?./*@member*/twice`,
      ts: (x) =>
        `((head: (n: number) => number, receiver: typeof tools | undefined) => (v: number) => ((w: number) => receiver?./*@member*/twice(w))(head(v)))(adder(${x}), /*@call*/maybe(/*@arg*/flip()))`,
    },
    {
      id: "memberFirst",
      title: "a member step first, bound to its receiver at composition",
      In: "number",
      inputs: "[2, 7]",
      tt: (x) => `flow |> note("receiver", /*@use*/tools)./*@member*/twice |> /*@call*/adder(${x})`,
      ts: (x) =>
        `((receiver: typeof tools, second: (n: number) => number) => (v: number) => second(receiver./*@member*/twice(v)))(note("receiver", /*@use*/tools), /*@call*/adder(${x}))`,
    },
    {
      id: "postfixFirst",
      title: "a postfix method step first",
      In: "number",
      inputs: "[1]",
      only: ["declarationInitializer", "callArgument", "arrowBody", "classField", "topLevel", "matchArm"],
      rejects: { all: "flow-first-step-method" },
      tt: (x) => `flow |> .toFixed(1) |> adder(${x})`,
      ts: () => "undefined",
    },
    {
      id: "optionalFirst",
      title: "an optional-chain step first",
      In: "number",
      inputs: "[1]",
      only: ["declarationInitializer", "returnOperand", "parameterDefault", "objectProperty", "topLevel", "loopBody"],
      rejects: { all: "flow-first-step-method" },
      tt: (x) => `flow |> maybe(true)?.twice |> adder(${x})`,
      ts: () => "undefined",
    },
  ],
};
