export default {
  construct: "flow",
  kind: "value",
  lowPrecedence: true,
  skip: ["templateLiteral"],
  forms: [
    {
      id: "twoSteps",
      title: "two steps composed, the second built from the operand",
      In: "number",
      inputs: "[2, 5]",
      tt: (x) => `flow |> double |> adder(${x})`,
      ts: (x) => `((second: (n: number) => number) => (v: number) => second(double(v)))(adder(${x}))`,
    },
    {
      id: "firstStepExpression",
      title: "a first step that is a call, evaluated at composition",
      In: "number",
      inputs: "[3, -4]",
      tt: (x) => `flow |> adder(${x}) |> String`,
      ts: (x) => `((first: (n: number) => number) => (v: number) => String(first(v)))(adder(${x}))`,
    },
    {
      id: "oneStep",
      title: "a single step, which is the step itself",
      In: "number",
      inputs: "[7, 1]",
      tt: (x) => `flow |> adder(${x})`,
      ts: (x) => `adder(${x})`,
    },
    {
      id: "postfixLater",
      title: "a later postfix step",
      In: "number",
      inputs: "[1.5, 2]",
      tt: (x) => `flow |> adder(${x}) |> .toFixed(1)`,
      ts: (x) => `((first: (n: number) => number) => (v: number) => first(v).toFixed(1))(adder(${x}))`,
    },
    {
      id: "memberLater",
      title: "a later member step whose receiver is read at composition",
      In: "number",
      inputs: "[2, 3]",
      tt: (x) => `flow |> adder(${x}) |> note("receiver", tools).twice`,
      ts: (x) =>
        `((first: (n: number) => number, receiver: typeof tools) => (v: number) => receiver.twice(first(v)))(adder(${x}), note("receiver", tools))`,
    },
    {
      id: "optionalLater",
      title: "a later optional-chain step whose receiver is read at composition",
      In: "number",
      inputs: "[4, 6, 8]",
      tt: (x) => `flow |> adder(${x}) |> maybe(flip())?.twice`,
      ts: (x) =>
        `((first: (n: number) => number, receiver: typeof tools | undefined) => (v: number) => ((w: number) => receiver?.twice(w))(first(v)))(adder(${x}), maybe(flip()))`,
    },
    {
      id: "memberFirst",
      title: "a member step first, bound to its receiver at composition",
      In: "number",
      inputs: "[2, 7]",
      tt: (x) => `flow |> note("receiver", tools).twice |> adder(${x})`,
      ts: (x) =>
        `((receiver: typeof tools, second: (n: number) => number) => (v: number) => second(receiver.twice(v)))(note("receiver", tools), adder(${x}))`,
    },
    {
      id: "postfixFirst",
      title: "a postfix method step first",
      In: "number",
      inputs: "[1]",
      only: ["declarationInitializer", "callArgument", "arrowBody", "classField", "topLevel", "matchArm"],
      rejects: { all: "flow-first-step-method" },
      tt: (x) => `flow |> .toFixed(1) |> adder(${x})`,
      ts: () => "undefined",
    },
    {
      id: "optionalFirst",
      title: "an optional-chain step first",
      In: "number",
      inputs: "[1]",
      only: ["declarationInitializer", "returnOperand", "parameterDefault", "objectProperty", "topLevel", "loopBody"],
      rejects: { all: "flow-first-step-method" },
      tt: (x) => `flow |> maybe(true)?.twice |> adder(${x})`,
      ts: () => "undefined",
    },
  ],
};
