import { variant } from "./variants.mjs";

const token = variant("Token", [
  ["Num", [["value", "number"]]],
  ["Neg", [["value", "number"]]],
  ["Word", [["text", "string"]]],
]);
const shape = variant("Shape", [
  ["Circle", [["r", "number"]]],
  ["Rect", [["w", "number"], ["h", "number"]]],
  ["Point", null],
]);

export default {
  construct: "letElse",
  kind: "statement",
  jsx: true,
  forms: [
    {
      id: "const",
      title: "a const binding with the host's exit in its else",
      In: "number",
      inputs: "[2, -1]",
      tt: (x, t, exit) => `const Ok(/*@field*/value: /*@bind*/v) = /*@call*/read(/*@arg*/${x}) else { ${exit} };`,
      ts: (x, [t], exit) => `const ${t} = /*@call*/read(/*@arg*/${x});\nif (${t}.kind !== "Ok") { ${exit} }\nconst /*@bind*/v = ${t}./*@field*/value;`,
      result: "v",
      hoisted: '"bound"',
      unbraced: "let-else-placement",
      temps: 1,
    },
    {
      id: "let",
      title: "a let binding reassigned after the test",
      In: "number",
      inputs: "[3, -3]",
      tt: (x, t, exit) => `let Ok(value: /*@bind*/v) = read(${x}) else { ${exit} };\nv = note("reassigned", /*@use*/v + 1);`,
      ts: (x, [t], exit) => `const ${t} = read(${x});\nif (${t}.kind !== "Ok") { ${exit} }\nlet /*@bind*/v = ${t}.value;\nv = note("reassigned", /*@use*/v + 1);`,
      result: "v",
      hoisted: '"bound"',
      unbraced: "let-else-placement",
      temps: 1,
    },
    {
      id: "var",
      title: "a var binding, allowed as an unbraced body",
      In: "number",
      inputs: "[4, -4]",
      tt: (x, t, exit) => `var Ok(value: /*@bind*/v) = /*@call*/read(${x}) else { ${exit} };`,
      ts: (x, [t], exit, c) =>
        c.unbraced
          ? `{ const ${t} = /*@call*/read(${x});\nif (${t}.kind !== "Ok") { ${exit} }\nvar /*@bind*/v = ${t}.value; }`
          : `const ${t} = /*@call*/read(${x});\nif (${t}.kind !== "Ok") { ${exit} }\nvar /*@bind*/v = ${t}.value;`,
      result: "v",
      hoisted: "v!",
      temps: 1,
    },
    {
      id: "throwingElse",
      title: "an else block that throws",
      In: "number",
      inputs: "[5, -5]",
      tt: (x) => `const Ok(value: /*@bind*/v) = read(${x}) else { throw new /*@call*/Error(/*@arg*/note("else", "thrown")); };`,
      ts: (x, [t]) =>
        `const ${t} = read(${x});\nif (${t}.kind !== "Ok") { throw new /*@call*/Error(/*@arg*/note("else", "thrown")); }\nconst /*@bind*/v = ${t}.value;`,
      result: "v",
      hoisted: '"bound"',
      unbraced: "let-else-placement",
      temps: 1,
    },
    {
      id: "orPattern",
      title: "an or-pattern whose alternatives bind the same field",
      decls: [token],
      In: "Token",
      inputs: '[Token.Num(1), Token.Neg(-2), Token.Word("w")]',
      tt: (x, t, exit) => `const Num(/*@bind*/value) | Neg(value) = ${x} else { ${exit} };`,
      ts: (x, [t], exit) => `const ${t} = ${x};\nif (${t}.kind !== "Num" && ${t}.kind !== "Neg") { ${exit} }\nconst value = ${t}.value;`,
      edit: (x, [t], exit) => `const ${t} = ${x};\nif (${t}.kind !== "Num" && ${t}.kind !== "Neg") { ${exit} }\nconst { /*@bind*/value } = ${t};`,
      result: "value",
      hoisted: '"bound"',
      unbraced: "let-else-placement",
      temps: 1,
    },
    {
      id: "aliasedFields",
      title: "fields bound under aliases",
      decls: [shape],
      In: "Shape",
      inputs: "[Shape.Rect(2, 3), Shape.Circle(1), Shape.Point]",
      tt: (x, t, exit) => `const Rect(/*@field*/h: /*@bind*/height, w: /*@bind2*/width) = ${x} else { ${exit} };`,
      ts: (x, [t], exit) => `const ${t} = ${x};\nif (${t}.kind !== "Rect") { ${exit} }\nconst height = ${t}.h, width = ${t}.w;`,
      edit: (x, [t], exit) => `const ${t} = ${x};\nif (${t}.kind !== "Rect") { ${exit} }\nconst { /*@field*/h: /*@bind*/height, w: /*@bind2*/width } = ${t};`,
      result: "[width, height]",
      hoisted: '"bound"',
      unbraced: "let-else-placement",
      temps: 1,
    },
    {
      id: "objectInitializer",
      title: "an object literal initializer",
      In: "number",
      inputs: "[7, 8]",
      tt: (x, t, exit) => `const Some(value: /*@bind*/v) = { kind: "Some" as const, value: ${x} } else { ${exit} };`,
      ts: (x, [t], exit) => `const ${t} = { kind: "Some" as const, value: ${x} };\nif (${t}.kind !== "Some") { ${exit} }\nconst /*@bind*/v = ${t}.value;`,
      result: "v",
      hoisted: '"bound"',
      unbraced: "let-else-placement",
      temps: 1,
    },
  ],
};
