export default {
  construct: "pipeline",
  kind: "value",
  jsx: true,
  lowPrecedence: true,
  forms: [
    {
      id: "callStep",
      title: "a step that names a function",
      In: "number",
      inputs: "[2, 5]",
      tt: (x) => `${x} |> /*@call*/double`,
      ts: (x) => `/*@call*/double(${x})`,
    },
    {
      id: "chain",
      title: "a chain of function and postfix steps",
      In: "number",
      inputs: "[3, 12]",
      tt: (x) => `${x} |> /*@call*/double |> /*@call2*/String |> ./*@member*/padStart(/*@arg*/4, "*")`,
      ts: (x) => `/*@call2*/String(/*@call*/double(${x}))./*@member*/padStart(/*@arg*/4, "*")`,
    },
    {
      id: "postfixStep",
      title: "a postfix step on the piped value",
      In: "number",
      inputs: "[1.25, 7]",
      tt: (x) => `${x} |> ./*@member*/toFixed(/*@arg*/1)`,
      ts: (x) => `(${x})./*@member*/toFixed(/*@arg*/1)`,
    },
    {
      id: "stepAfterValue",
      title: "a step expression evaluated after the piped value",
      In: "number",
      inputs: "[4, -1]",
      tt: (x) => `${x} |> /*@call*/adder(/*@arg*/note("step", 3))`,
      ts: (x, [t]) => `(${t} = ${x}, /*@call*/adder(/*@arg*/note("step", 3))(${t}))`,
    },
    {
      id: "memberStep",
      title: "a member step called on its receiver, after the value",
      In: "number",
      inputs: "[2, 6]",
      tt: (x) => `${x} |> note("receiver", /*@use*/tools)./*@member*/twice`,
      ts: (x, [t]) => `(${t} = ${x}, note("receiver", /*@use*/tools)./*@member*/twice(${t}))`,
    },
    {
      id: "optionalMemberStep",
      title: "an optional-chain step that runs and one that short-circuits",
      In: "number",
      inputs: "[3, 4, 5]",
      tt: (x) => `${x} |> /*@call*/maybe(/*@arg*/flip())?./*@member*/twice`,
      ts: (x, [t]) => `(${t} = ${x}, /*@call*/maybe(/*@arg*/flip())?./*@member*/twice(${t}))`,
    },
    {
      id: "optionalTail",
      title: "a step that is an optional postfix tail",
      In: "number",
      inputs: "[2.5, -3]",
      tt: (x) => `/*@call*/positive(${x}) |> ?./*@member*/toFixed(2)`,
      ts: (x) => `/*@call*/positive(${x})?./*@member*/toFixed(2)`,
    },
    {
      id: "arrowStep",
      title: "a parenthesized arrow step",
      In: "number",
      inputs: "[8, 9]",
      tt: (x) => `${x} |> ((/*@bind*/n: number) => note("arrow", /*@use*/n + 1))`,
      ts: (x, [t]) => `(${t} = ${x}, ((/*@bind*/n: number) => note("arrow", /*@use*/n + 1))(${t}))`,
    },
    {
      id: "nullishStep",
      title: "a step that extends over ??",
      In: "number",
      inputs: "[10, 20]",
      tt: (x) => `${x} |> /*@call*/lookup(flip()) ?? /*@use*/double`,
      ts: (x, [t]) => `(${t} = ${x}, (/*@call*/lookup(flip()) ?? /*@use*/double)(${t}))`,
    },
    {
      id: "assertionThenStep",
      title: "an as-assertion that ends a step, then another step",
      In: "number",
      inputs: "[123, 4]",
      tt: (x) => `${x} |> /*@call*/String as string |> ./*@member*/length`,
      ts: (x) => `(/*@call*/String(${x}) as string)./*@member*/length`,
    },
    {
      id: "curriedStd",
      title: "curried standard-library steps",
      In: "number",
      inputs: "[5, 0]",
      decls: [{ tt: 'import * as Option from "@tt/std/option";', ts: "" }],
      tt: (x) =>
        `Option.fromNullable(${x} || null) |> Option.mapP((/*@bind*/n: number) => note("map", /*@use*/n * 3)) |> Option.unwrapOrP(-1)`,
      ts: (x, [t]) => `(${t} = ${x} || null, ${t} === null ? -1 : note("map", ${t} * 3))`,
      edit: (x, [t]) => `(${t} = ${x} || null, ${t} === null ? -1 : ((/*@bind*/n: number) => note("map", /*@use*/n * 3))(${t}))`,
    },
    {
      id: "overloadedStep",
      title: "a step that names an overloaded function, resolved against the piped value",
      In: "number",
      inputs: "[4, 12]",
      tt: (x) => `${x} |> /*@call*/shape |> ./*@member*/length`,
      ts: (x) => `/*@call*/shape(${x})./*@member*/length`,
    },
    {
      id: "genericStep",
      title: "a step that names a generic function, instantiated by the piped value",
      In: "number",
      inputs: "[6, -2]",
      tt: (x) => `${x} |> /*@call*/keep |> double`,
      ts: (x) => `double(/*@call*/keep(${x}))`,
    },
  ],
};
