export default {
  construct: "pipeline",
  kind: "value",
  jsx: true,
  lowPrecedence: true,
  forms: [
    {
      id: "callStep",
      title: "a step that names a function",
      In: "number",
      inputs: "[2, 5]",
      tt: (x) => `${x} |> double`,
      ts: (x) => `double(${x})`,
    },
    {
      id: "chain",
      title: "a chain of function and postfix steps",
      In: "number",
      inputs: "[3, 12]",
      tt: (x) => `${x} |> double |> String |> .padStart(4, "*")`,
      ts: (x) => `String(double(${x})).padStart(4, "*")`,
    },
    {
      id: "postfixStep",
      title: "a postfix step on the piped value",
      In: "number",
      inputs: "[1.25, 7]",
      tt: (x) => `${x} |> .toFixed(1)`,
      ts: (x) => `(${x}).toFixed(1)`,
    },
    {
      id: "stepAfterValue",
      title: "a step expression evaluated after the piped value",
      In: "number",
      inputs: "[4, -1]",
      tt: (x) => `${x} |> adder(note("step", 3))`,
      ts: (x, [t]) => `(${t} = ${x}, adder(note("step", 3))(${t}))`,
    },
    {
      id: "memberStep",
      title: "a member step called on its receiver, after the value",
      In: "number",
      inputs: "[2, 6]",
      tt: (x) => `${x} |> note("receiver", tools).twice`,
      ts: (x, [t]) => `(${t} = ${x}, note("receiver", tools).twice(${t}))`,
    },
    {
      id: "optionalMemberStep",
      title: "an optional-chain step that runs and one that short-circuits",
      In: "number",
      inputs: "[3, 4, 5]",
      tt: (x) => `${x} |> maybe(flip())?.twice`,
      ts: (x, [t]) => `(${t} = ${x}, maybe(flip())?.twice(${t}))`,
    },
    {
      id: "optionalTail",
      title: "a step that is an optional postfix tail",
      In: "number",
      inputs: "[2.5, -3]",
      tt: (x) => `positive(${x}) |> ?.toFixed(2)`,
      ts: (x) => `positive(${x})?.toFixed(2)`,
    },
    {
      id: "arrowStep",
      title: "a parenthesized arrow step",
      In: "number",
      inputs: "[8, 9]",
      tt: (x) => `${x} |> ((n: number) => note("arrow", n + 1))`,
      ts: (x, [t]) => `(${t} = ${x}, ((n: number) => note("arrow", n + 1))(${t}))`,
    },
    {
      id: "nullishStep",
      title: "a step that extends over ??",
      In: "number",
      inputs: "[10, 20]",
      tt: (x) => `${x} |> lookup(flip()) ?? double`,
      ts: (x, [t]) => `(${t} = ${x}, (lookup(flip()) ?? double)(${t}))`,
    },
    {
      id: "assertionThenStep",
      title: "an as-assertion that ends a step, then another step",
      In: "number",
      inputs: "[123, 4]",
      tt: (x) => `${x} |> String as string |> .length`,
      ts: (x) => `(String(${x}) as string).length`,
    },
    {
      id: "curriedStd",
      title: "curried standard-library steps",
      In: "number",
      inputs: "[5, 0]",
      decls: [{ tt: 'import * as Option from "@tt/std/option";', ts: "" }],
      tt: (x) => `Option.fromNullable(${x} || null) |> Option.mapP((n: number) => note("map", n * 3)) |> Option.unwrapOrP(-1)`,
      ts: (x, [t]) => `(${t} = ${x} || null, ${t} === null ? -1 : note("map", ${t} * 3))`,
    },
  ],
};
