export default [
  {
    construct: "try",
    kind: "value",
    jsx: true,
    target: true,
    rejects: { yield: "try-placement" },
    forms: [
      {
        id: "operand",
        title: "the value form on a call",
        In: "number",
        inputs: "[2, -1]",
        tt: (x) => `try /*@call*/read(/*@arg*/${x})`,
        ts: (x) => `unwrap(/*@call*/read(/*@arg*/${x}))`,
      },
      {
        id: "binaryOperand",
        title: "the value form binding tighter than a binary operator",
        In: "number",
        inputs: "[3, -2]",
        tt: (x) => `try /*@call*/read(${x}) * 10`,
        ts: (x) => `(unwrap(/*@call*/read(${x})) * 10)`,
      },
      {
        id: "siblings",
        title: "two sibling value forms, left to right",
        In: "number",
        inputs: "[4, -4]",
        tt: (x) => `(try read(${x})) + (try /*@call*/read(/*@arg*/note("second", 5)))`,
        ts: (x) => `(unwrap(read(${x})) + unwrap(/*@call*/read(/*@arg*/note("second", 5))))`,
      },
      {
        id: "parenthesized",
        title: "a parenthesized conditional operand",
        In: "number",
        inputs: "[6, -6]",
        tt: (x) => `try (/*@call*/flip() ? read(${x}) : read(/*@arg*/note("fallback", -9)))`,
        ts: (x) => `unwrap(/*@call*/flip() ? read(${x}) : read(/*@arg*/note("fallback", -9)))`,
      },
      {
        id: "memberOfValue",
        title: "a member read on the parenthesized value form",
        In: "number",
        inputs: "[1.5, -1]",
        tt: (x) => `(try read(${x}))./*@member*/toFixed(/*@arg*/2)`,
        ts: (x) => `unwrap(read(${x}))./*@member*/toFixed(/*@arg*/2)`,
      },
      {
        id: "matchOperand",
        title: "a match as the operand",
        In: "number",
        inputs: "[1, 2, -3]",
        tt: (x) => `try match (${x}) { 1 => /*@call*/read(/*@arg*/note("one", 10)), _ => read(note("other", -10)) }`,
        ts: (x, [t]) => `unwrap((${t} = ${x}, ${t} === 1 ? read(note("one", 10)) : read(note("other", -10))))`,
        edit: (x, [t]) => `unwrap(((${t}: number) => (${t} === 1 ? /*@call*/read(/*@arg*/note("one", 10)) : read(note("other", -10))))(${x}))`,
      },
    ],
  },
  {
    construct: "tryStatement",
    kind: "statement",
    jsx: true,
    target: true,
    rejects: { yield: "try-placement" },
    forms: [
      {
        id: "propagate",
        title: "the statement form that only propagates",
        In: "number",
        inputs: "[2, -1]",
        tt: (x) => `try /*@call*/read(/*@arg*/${x});`,
        ts: (x) => `unwrap(/*@call*/read(/*@arg*/${x}));`,
        result: '"checked"',
        hoisted: '"checked"',
      },
      {
        id: "declaration",
        title: "a declaration initialized by the statement form",
        In: "number",
        inputs: "[5, -5]",
        tt: (x) => `const /*@bind*/checked = try /*@call*/read(${x});`,
        ts: (x) => `const /*@bind*/checked = unwrap(/*@call*/read(${x}));`,
        result: "checked",
        hoisted: '"checked"',
        unbraced: "try-placement",
      },
    ],
  },
];
