// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_ifLetBody_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, positive, read } from "./harness.js";
const inputs: number[] = [2.5, -3];
function probe(input: number) {
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, /*call*/positive(note("operand", /*operand*/input))?./*member*/toFixed(2)];
  }
  return null;
}
