// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_memberStep_jsxChild_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, risky, tools, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [2, 6];
function probe(input: number) {
  try {
    return <p>{(t0 = risky(/*operand*/input), note("receiver", /*use*/tools)./*member*/twice(t0))}</p>;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
