// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_arrowStep_nullish_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, risky } from "./harness.js";
let t0: any;
const inputs: number[] = [8, 9];
function probe(input: number) {
  try {
    return (flip() ? null : note("left", "set")) ?? (t0 = risky(/*operand*/input), ((/*bind*/n: number) => note("arrow", /*use*/n + 1))(t0));
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
