// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_loopBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, positive } from "./harness.js";
const inputs: number[] = [2.5, -3];
function probe(input: number) {
  try {
    const collected: unknown[] = [];
    for (let round = 0; round < 2; round++) {
      collected.push(/*call*/positive(risky(/*operand*/input))?./*member*/toFixed(2));
    }
    return collected;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
