// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_objectProperty_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, positive } from "./harness.js";
const inputs: number[] = [2.5, -3];
function probe(input: number) {
  return { a: note("a", 1), value: /*call*/positive(first(...[/*operand*/input]))?./*member*/toFixed(2), c: note("c", 3) };
}
