// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, later, double, report } from "./harness.js";
const inputs: number[] = [3, 12];
let input: number = inputs[0]!;
const top0 = /*call2*/String(/*call*/double(await later(/*operand*/input)))./*member*/padStart(/*arg*/4, "*");
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = String(double(await later(input))).padStart(4, "*");
report("topLevel", input, text(top1));
