// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_memberStep_awaitOperand_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, tools } from "./harness.js";
let t0: any;
const inputs: number[] = [2, 6];
async function probe(input: number) {
  try {
    return await ((t0 = note("operand", /*operand*/input), note("receiver", /*use*/tools)./*member*/twice(t0)));
  } finally {
    note("finally", 0);
  }
}
