// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_arrowStep_loopBody_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
let t0: any;
const inputs: number[] = [8, 9];
function probe(input: number) {
  const collected: unknown[] = [];
  for (let round = 0; round < 2; round++) {
    collected.push((t0 = box(/*operand*/input)?.inner.value!, ((/*bind*/n: number) => note("arrow", /*use*/n + 1))(t0)));
  }
  return collected;
}
