// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_arrowStep_ifLetBody_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, read } from "./harness.js";
let t0: any;
const inputs: number[] = [8, 9];
function probe(input: number) {
  using res = resource("res");
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, (t0 = note("operand", /*operand*/input), ((/*bind*/n: number) => note("arrow", /*use*/n + 1))(t0))];
  }
  return null;
}
