// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_memberStep_jsxConditional_using.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, flip, tools, resource, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [2, 6];
function probe(input: number) {
  using res = resource("res");
  return <p>{flip() && (t0 = note("operand", /*operand*/input), note("receiver", /*use*/tools)./*member*/twice(t0))}</p>;
}
