// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_arrowBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, double } from "./harness.js";
const inputs: number[] = [3, 12];
function probe(input: number) {
  try {
    const inner = (input: number) => /*call2*/String(/*call*/double(risky(/*operand*/input)))./*member*/padStart(/*arg*/4, "*");
    return inner(input);
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
