// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_callStep_jsxConditional_yield.ttx; it shares the case's other units.
// @filename: main.tsx
import { flip, double, element, Fragment } from "./harness.js";
const inputs: number[] = [2, 5];
function* probe(input: number): Generator<unknown, unknown, number> {
  return <p>{flip() && /*call*/double((yield /*operand*/input))}</p>;
}
