// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_arrowStep_method_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, read } from "./harness.js";
let t0: any;
const inputs: number[] = [8, 9];
function probe(input: number) {
  class Holder {
    tag = "holder";
    async read(input: number) {
      note("this", this.tag);
      return (t0 = await later(/*operand*/input), ((/*bind*/n: number) => note("arrow", /*use*/n + 1))(t0));
    }
  }
  return new Holder().read(input);
}
