// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_jsxTernary_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, flip, risky, positive, element, Fragment } from "./harness.js";
const inputs: number[] = [2.5, -3];
function probe(input: number) {
  try {
    return <p>{flip() ? /*call*/positive(risky(/*operand*/input))?./*member*/toFixed(2) : <i>none</i>}</p>;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
