// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_jsxNested_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, element, Fragment } from "./harness.js";
const inputs: number[] = [123, 4];
function probe(input: number) {
  try {
    return <ul><li>{note("first", 1)}</li><li>{(/*call*/String(note("operand", /*operand*/input)) as string)./*member*/length}</li></ul>;
  } finally {
    note("finally", 0);
  }
}
