// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_awaitOperand_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, positive, resource } from "./harness.js";
const inputs: number[] = [2.5, -3];
async function probe(input: number) {
  using res = resource("res");
  return await (/*call*/positive(note("operand", /*operand*/input))?./*member*/toFixed(2));
}
