// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_ifLetBody_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, read } from "./harness.js";
const inputs: number[] = [123, 4];
function probe(input: number) {
  try {
    const head = read(note("head", 1));
    if (head.kind === "Ok") {
      const n = head.value;
      return [n, (/*call*/String(note("operand", /*operand*/input)) as string)./*member*/length];
    }
    return null;
  } finally {
    note("finally", 0);
  }
}
