// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_arrowBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky } from "./harness.js";
const inputs: number[] = [123, 4];
function probe(input: number) {
  try {
    const inner = (input: number) => (/*call*/String(risky(/*operand*/input)) as string)./*member*/length;
    return inner(input);
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
