// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_arrowStep_callArgument_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack } from "./harness.js";
let t0: any;
const inputs: number[] = [8, 9];
function probe(input: number) {
  try {
    return pack(note("a", 1), (t0 = note("operand", /*operand*/input), ((/*bind*/n: number) => note("arrow", /*use*/n + 1))(t0)), note("c", 3));
  } finally {
    note("finally", 0);
  }
}
