// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_jsxNested_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, double, keep, element, Fragment } from "./harness.js";
const inputs: number[] = [6, -2];
function probe(input: number) {
  try {
    return <ul><li>{note("first", 1)}</li><li>{double(/*call*/keep(note("operand", /*operand*/input)))}</li></ul>;
  } finally {
    note("finally", 0);
  }
}
