// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_logicalAnd_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, risky, double, keep } from "./harness.js";
const inputs: number[] = [6, -2];
function probe(input: number) {
  try {
    return flip() && double(/*call*/keep(risky(/*operand*/input)));
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
