// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_memberStep_jsxComponentProp_yield.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, tools, Show, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [2, 6];
function* probe(input: number): Generator<unknown, unknown, number> {
  return <Show /*attrHost*/value={(t0 = (yield /*operand*/input), note("receiver", /*use*/tools)./*member*/twice(t0))} />;
}
