// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_memberStep_jsxSpreadAttribute_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, later, tools, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [2, 6];
async function probe(input: number) {
  return <div {...{ value: (t0 = await later(/*operand*/input), note("receiver", /*use*/tools)./*member*/twice(t0)) }} />;
}
