// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalMemberStep_returnOperand_spread.tt; it shares the case's other units.
// @filename: main.ts
import { flip, first, maybe } from "./harness.js";
let t0: any;
const inputs: number[] = [3, 4, 5];
function probe(input: number) {
  return (t0 = first(...[/*operand*/input]), /*call*/maybe(/*arg*/flip())?./*member*/twice(t0));
}
