// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_nullish_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, box, double, keep } from "./harness.js";
const inputs: number[] = [6, -2];
function probe(input: number) {
  return (flip() ? null : note("left", "set")) ?? double(/*call*/keep(box(/*operand*/input)?.inner.value!));
}
