// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_postfixStep_topLevel_spread.tt; it shares the case's other units.
// @filename: main.ts
import { text, first, report } from "./harness.js";
const inputs: number[] = [1.25, 7];
let input: number = inputs[0]!;
const top0 = (first(...[/*operand*/input]))./*member*/toFixed(/*arg*/1);
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = (first(...[input])).toFixed(1);
report("topLevel", input, text(top1));
