// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalMemberStep_getter_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { flip, box, maybe } from "./harness.js";
let t0: any;
const inputs: number[] = [3, 4, 5];
function probe(input: number) {
  const holder = {
    get field() {
      return (t0 = box(/*operand*/input)?.inner.value!, /*call*/maybe(/*arg*/flip())?./*member*/twice(t0));
    },
  };
  return holder.field;
}
