// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_callArgument_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, risky, double } from "./harness.js";
const inputs: number[] = [3, 12];
function probe(input: number) {
  try {
    return pack(note("a", 1), /*call2*/String(/*call*/double(risky(/*operand*/input)))./*member*/padStart(/*arg*/4, "*"), note("c", 3));
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
