// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_arrowStep_arrowBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later } from "./harness.js";
let t0: any;
const inputs: number[] = [8, 9];
function probe(input: number) {
  const inner = async (input: number) => (t0 = await later(/*operand*/input), ((/*bind*/n: number) => note("arrow", /*use*/n + 1))(t0));
  return inner(input);
}
