// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_awaitOperand_spread.tt; it shares the case's other units.
// @filename: main.ts
import { first, double } from "./harness.js";
const inputs: number[] = [3, 12];
async function probe(input: number) {
  return await (/*call2*/String(/*call*/double(first(...[/*operand*/input])))./*member*/padStart(/*arg*/4, "*"));
}
