// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_jsxFragment_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, risky, double, element, Fragment } from "./harness.js";
const inputs: number[] = [3, 12];
function probe(input: number) {
  try {
    return <>{note("before", "[")}{/*call2*/String(/*call*/double(risky(/*operand*/input)))./*member*/padStart(/*arg*/4, "*")}{note("after", "]")}</>;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
