// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_nullish_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, double, keep } from "./harness.js";
const inputs: number[] = [6, -2];
function probe(input: number) {
  try {
    return (flip() ? null : note("left", "set")) ?? double(/*call*/keep(note("operand", /*operand*/input)));
  } finally {
    note("finally", 0);
  }
}
