// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_overloadedStep_jsxSpreadAttribute_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, risky, shape, element, Fragment } from "./harness.js";
const inputs: number[] = [4, 12];
function probe(input: number) {
  try {
    return <div {...{ value: /*call*/shape(risky(/*operand*/input))./*member*/length }} />;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
