// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalMemberStep_jsxFragment_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, later, flip, maybe, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [3, 4, 5];
async function probe(input: number) {
  return <>{note("before", "[")}{(t0 = await later(/*operand*/input), /*call*/maybe(/*arg*/flip())?./*member*/twice(t0))}{note("after", "]")}</>;
}
