// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_arrowStep_callArgument_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack } from "./harness.js";
let t0: any;
const inputs: number[] = [8, 9];
function* probe(input: number): Generator<unknown, unknown, number> {
  return pack(note("a", 1), (t0 = (yield /*operand*/input), ((/*bind*/n: number) => note("arrow", /*use*/n + 1))(t0)), note("c", 3));
}
