// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_awaitOperand_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [123, 4];
async function probe(input: number) {
  return await ((/*call*/String(note("operand", /*operand*/input)) as string)./*member*/length);
}
