// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_nullishStep_templateLiteral_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, double, lookup } from "./harness.js";
let t0: any;
const inputs: number[] = [10, 20];
function* probe(input: number): Generator<unknown, unknown, number> {
  return `<${note("left", "L")}|${(t0 = (yield /*operand*/input), (/*call*/lookup(flip()) ?? /*use*/double)(t0))}|${note("right", "R")}>`;
}
