// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_curriedStd_topLevel_using.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, resource, report } from "./harness.js";
let t0: any, t1: any;
const inputs: number[] = [5, 0];
let input: number = inputs[0]!;
using res = resource("res");
const top0 = (t0 = note("operand", /*operand*/input) || null, t0 === null ? -1 : ((/*bind*/n: number) => note("map", /*use*/n * 3))(t0));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = (t1 = note("operand", input) || null, t1 === null ? -1 : ((n: number) => note("map", n * 3))(t1));
report("topLevel", input, text(top1));
