// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_templateLiteral_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box, double } from "./harness.js";
const inputs: number[] = [3, 12];
function probe(input: number) {
  return `<${note("left", "L")}|${/*call2*/String(/*call*/double(box(/*operand*/input)?.inner.value!))./*member*/padStart(/*arg*/4, "*")}|${note("right", "R")}>`;
}
