// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_callStep_method_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, double, read } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  try {
    class Holder {
      tag = "holder";
      read(input: number) {
        note("this", this.tag);
        return /*call*/double(note("operand", /*operand*/input));
      }
    }
    return new Holder().read(input);
  } finally {
    note("finally", 0);
  }
}
