// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_method_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, positive, read } from "./harness.js";
const inputs: number[] = [2.5, -3];
function probe(input: number) {
  try {
    class Holder {
      tag = "holder";
      read(input: number) {
        note("this", this.tag);
        return /*call*/positive(risky(/*operand*/input))?./*member*/toFixed(2);
      }
    }
    return new Holder().read(input);
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
