// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_nullishStep_jsxChild_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { later, flip, double, lookup, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [10, 20];
async function probe(input: number) {
  return <p>{(t0 = await later(/*operand*/input), (/*call*/lookup(flip()) ?? /*use*/double)(t0))}</p>;
}
