// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_overloadedStep_returnOperand_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box, shape } from "./harness.js";
const inputs: number[] = [4, 12];
function probe(input: number) {
  return /*call*/shape(box(/*operand*/input)?.inner.value!)./*member*/length;
}
