// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_awaitOperand_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, double, keep } from "./harness.js";
const inputs: number[] = [6, -2];
async function probe(input: number) {
  try {
    return await (double(/*call*/keep(note("operand", /*operand*/input))));
  } finally {
    note("finally", 0);
  }
}
