// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_callStep_jsxComponentProp_using.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, double, resource, Show, element, Fragment } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  using res = resource("res");
  return <Show /*attrHost*/value={/*call*/double(note("operand", /*operand*/input))} />;
}
