// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_callStep_arrowBody_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, double } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  const inner = (input: number) => /*call*/double(note("operand", /*operand*/input));
  return inner(input);
}
