// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_postfixStep_jsxFragment_using.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, resource, element, Fragment } from "./harness.js";
const inputs: number[] = [1.25, 7];
function probe(input: number) {
  using res = resource("res");
  return <>{note("before", "[")}{(note("operand", /*operand*/input))./*member*/toFixed(/*arg*/1)}{note("after", "]")}</>;
}
