// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_logicalAnd_yield.tt; it shares the case's other units.
// @filename: main.ts
import { flip } from "./harness.js";
const inputs: number[] = [123, 4];
function* probe(input: number): Generator<unknown, unknown, number> {
  return flip() && (/*call*/String((yield /*operand*/input)) as string)./*member*/length;
}
