// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_nullishStep_getter_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, double, lookup } from "./harness.js";
let t0: any;
const inputs: number[] = [10, 20];
function probe(input: number) {
  const holder = {
    get field() {
      return (t0 = note("operand", /*operand*/input), (/*call*/lookup(flip()) ?? /*use*/double)(t0));
    },
  };
  return holder.field;
}
