// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_stepAfterValue_topLevel_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, box, adder, report } from "./harness.js";
let t0: any, t1: any;
const inputs: number[] = [4, -1];
let input: number = inputs[0]!;
const top0 = (t0 = box(/*operand*/input)?.inner.value!, /*call*/adder(/*arg*/note("step", 3))(t0));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = (t1 = box(input)?.inner.value!, adder(note("step", 3))(t1));
report("topLevel", input, text(top1));
