// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_stepAfterValue_declarationInitializer_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder } from "./harness.js";
let t0: any;
const inputs: number[] = [4, -1];
function probe(input: number) {
  try {
    const value = (t0 = note("operand", /*operand*/input), /*call*/adder(/*arg*/note("step", 3))(t0));
    return value;
  } finally {
    note("finally", 0);
  }
}
