// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_overloadedStep_templateLiteral_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, shape } from "./harness.js";
const inputs: number[] = [4, 12];
async function probe(input: number) {
  return `<${note("left", "L")}|${/*call*/shape(await later(/*operand*/input))./*member*/length}|${note("right", "R")}>`;
}
