// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_objectProperty_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, double, keep } from "./harness.js";
const inputs: number[] = [6, -2];
async function probe(input: number) {
  return { a: note("a", 1), value: double(/*call*/keep(await later(/*operand*/input))), c: note("c", 3) };
}
