// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, later, report } from "./harness.js";
const inputs: number[] = [123, 4];
let input: number = inputs[0]!;
const top0 = (/*call*/String(await later(/*operand*/input)) as string)./*member*/length;
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = (String(await later(input)) as string).length;
report("topLevel", input, text(top1));
