// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_nullishStep_arrowBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { later, flip, double, lookup } from "./harness.js";
let t0: any;
const inputs: number[] = [10, 20];
function probe(input: number) {
  const inner = async (input: number) => (t0 = await later(/*operand*/input), (/*call*/lookup(flip()) ?? /*use*/double)(t0));
  return inner(input);
}
