// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_postfixStep_callArgument_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, resource } from "./harness.js";
const inputs: number[] = [1.25, 7];
function probe(input: number) {
  using res = resource("res");
  return pack(note("a", 1), (note("operand", /*operand*/input))./*member*/toFixed(/*arg*/1), note("c", 3));
}
