// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_getter_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource } from "./harness.js";
const inputs: number[] = [123, 4];
function probe(input: number) {
  using res = resource("res");
  const holder = {
    get field() {
      return (/*call*/String(note("operand", /*operand*/input)) as string)./*member*/length;
    },
  };
  return holder.field;
}
