// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_callArgument_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, pack } from "./harness.js";
const inputs: number[] = [123, 4];
async function probe(input: number) {
  return pack(note("a", 1), (/*call*/String(await later(/*operand*/input)) as string)./*member*/length, note("c", 3));
}
