// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalMemberStep_jsxChild_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { flip, first, maybe, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [3, 4, 5];
function probe(input: number) {
  return <p>{(t0 = first(...[/*operand*/input]), /*call*/maybe(/*arg*/flip())?./*member*/twice(t0))}</p>;
}
