// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_method_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, double, keep, read } from "./harness.js";
const inputs: number[] = [6, -2];
function probe(input: number) {
  class Holder {
    tag = "holder";
    async read(input: number) {
      note("this", this.tag);
      return double(/*call*/keep(await later(/*operand*/input)));
    }
  }
  return new Holder().read(input);
}
