// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_callArgument_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, box } from "./harness.js";
const inputs: number[] = [123, 4];
function probe(input: number) {
  return pack(note("a", 1), (/*call*/String(box(/*operand*/input)?.inner.value!) as string)./*member*/length, note("c", 3));
}
