// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_postfixStep_nullish_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, flip } from "./harness.js";
const inputs: number[] = [1.25, 7];
async function probe(input: number) {
  return (flip() ? null : note("left", "set")) ?? (await later(/*operand*/input))./*member*/toFixed(/*arg*/1);
}
