// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_jsxConditional_yield.ttx; it shares the case's other units.
// @filename: main.tsx
import { flip, element, Fragment } from "./harness.js";
const inputs: number[] = [123, 4];
function* probe(input: number): Generator<unknown, unknown, number> {
  return <p>{flip() && (/*call*/String((yield /*operand*/input)) as string)./*member*/length}</p>;
}
