// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_templateLiteral_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note, double, keep } from "./harness.js";
const inputs: number[] = [6, -2];
function* probe(input: number): Generator<unknown, unknown, number> {
  return `<${note("left", "L")}|${double(/*call*/keep((yield /*operand*/input)))}|${note("right", "R")}>`;
}
