// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_memberStep_arrowBody_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, tools } from "./harness.js";
let t0: any;
const inputs: number[] = [2, 6];
function probe(input: number) {
  const inner = (input: number) => (t0 = first(...[/*operand*/input]), note("receiver", /*use*/tools)./*member*/twice(t0));
  return inner(input);
}
