// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_method_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, double, read } from "./harness.js";
const inputs: number[] = [3, 12];
function probe(input: number) {
  class Holder {
    tag = "holder";
    async read(input: number) {
      note("this", this.tag);
      return /*call2*/String(/*call*/double(await later(/*operand*/input)))./*member*/padStart(/*arg*/4, "*");
    }
  }
  return new Holder().read(input);
}
