// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_arrowStep_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, report } from "./harness.js";
let t0: any, t1: any;
const inputs: number[] = [8, 9];
let input: number = inputs[0]!;
const top0 = (t0 = await later(/*operand*/input), ((/*bind*/n: number) => note("arrow", /*use*/n + 1))(t0));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = (t1 = await later(input), ((n: number) => note("arrow", n + 1))(t1));
report("topLevel", input, text(top1));
