// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_stepAfterValue_loopBody_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder } from "./harness.js";
let t0: any;
const inputs: number[] = [4, -1];
function* probe(input: number): Generator<unknown, unknown, number> {
  const collected: unknown[] = [];
  for (let round = 0; round < 2; round++) {
    collected.push((t0 = (yield /*operand*/input), /*call*/adder(/*arg*/note("step", 3))(t0)));
  }
  return collected;
}
