// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_stepAfterValue_method_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder, resource, read } from "./harness.js";
let t0: any;
const inputs: number[] = [4, -1];
function probe(input: number) {
  using res = resource("res");
  class Holder {
    tag = "holder";
    read(input: number) {
      note("this", this.tag);
      return (t0 = note("operand", /*operand*/input), /*call*/adder(/*arg*/note("step", 3))(t0));
    }
  }
  return new Holder().read(input);
}
