// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_returnOperand_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, positive } from "./harness.js";
const inputs: number[] = [2.5, -3];
function probe(input: number) {
  try {
    return /*call*/positive(note("operand", /*operand*/input))?./*member*/toFixed(2);
  } finally {
    note("finally", 0);
  }
}
