// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_jsxChild_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, positive, element, Fragment } from "./harness.js";
const inputs: number[] = [2.5, -3];
function probe(input: number) {
  try {
    return <p>{/*call*/positive(note("operand", /*operand*/input))?./*member*/toFixed(2)}</p>;
  } finally {
    note("finally", 0);
  }
}
