// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_jsxAttribute_using.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, positive, resource, element, Fragment } from "./harness.js";
const inputs: number[] = [2.5, -3];
function probe(input: number) {
  using res = resource("res");
  return <div /*attrHost*/data-value={/*call*/positive(note("operand", /*operand*/input))?./*member*/toFixed(2)} />;
}
