// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_method_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, read } from "./harness.js";
const inputs: number[] = [123, 4];
function probe(input: number) {
  class Holder {
    tag = "holder";
    async read(input: number) {
      note("this", this.tag);
      return (/*call*/String(await later(/*operand*/input)) as string)./*member*/length;
    }
  }
  return new Holder().read(input);
}
