// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_jsxAttribute_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { later, double, element, Fragment } from "./harness.js";
const inputs: number[] = [3, 12];
async function probe(input: number) {
  return <div /*attrHost*/data-value={/*call2*/String(/*call*/double(await later(/*operand*/input)))./*member*/padStart(/*arg*/4, "*")} />;
}
