// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_overloadedStep_topLevel_spread.tt; it shares the case's other units.
// @filename: main.ts
import { text, first, shape, report } from "./harness.js";
const inputs: number[] = [4, 12];
let input: number = inputs[0]!;
const top0 = /*call*/shape(first(...[/*operand*/input]))./*member*/length;
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = shape(first(...[input])).length;
report("topLevel", input, text(top1));
