// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_memberStep_method_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, tools, read } from "./harness.js";
let t0: any;
const inputs: number[] = [2, 6];
function probe(input: number) {
  try {
    class Holder {
      tag = "holder";
      read(input: number) {
        note("this", this.tag);
        return (t0 = risky(/*operand*/input), note("receiver", /*use*/tools)./*member*/twice(t0));
      }
    }
    return new Holder().read(input);
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
