// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_postfixStep_callArgument_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, box } from "./harness.js";
const inputs: number[] = [1.25, 7];
function probe(input: number) {
  return pack(note("a", 1), (box(/*operand*/input)?.inner.value!)./*member*/toFixed(/*arg*/1), note("c", 3));
}
