// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_callStep_jsxFragment_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, first, double, element, Fragment } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  return <>{note("before", "[")}{/*call*/double(first(...[/*operand*/input]))}{note("after", "]")}</>;
}
