// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_nullishStep_awaitOperand_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { flip, box, double, lookup } from "./harness.js";
let t0: any;
const inputs: number[] = [10, 20];
async function probe(input: number) {
  return await ((t0 = box(/*operand*/input)?.inner.value!, (/*call*/lookup(flip()) ?? /*use*/double)(t0)));
}
