// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_postfixStep_jsxSpreadAttribute_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, element, Fragment } from "./harness.js";
const inputs: number[] = [1.25, 7];
function probe(input: number) {
  try {
    return <div {...{ value: (note("operand", /*operand*/input))./*member*/toFixed(/*arg*/1) }} />;
  } finally {
    note("finally", 0);
  }
}
