// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_nullishStep_loopBody_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, double, lookup, resource } from "./harness.js";
let t0: any;
const inputs: number[] = [10, 20];
function probe(input: number) {
  using res = resource("res");
  const collected: unknown[] = [];
  for (let round = 0; round < 2; round++) {
    collected.push((t0 = note("operand", /*operand*/input), (/*call*/lookup(flip()) ?? /*use*/double)(t0)));
  }
  return collected;
}
