// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_postfixStep_declarationInitializer_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [1.25, 7];
function probe(input: number) {
  try {
    const value = (note("operand", /*operand*/input))./*member*/toFixed(/*arg*/1);
    return value;
  } finally {
    note("finally", 0);
  }
}
