// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_ifLetBody_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box, double, keep, read } from "./harness.js";
const inputs: number[] = [6, -2];
function probe(input: number) {
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, double(/*call*/keep(box(/*operand*/input)?.inner.value!))];
  }
  return null;
}
