// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_stepAfterValue_awaitOperand_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, adder } from "./harness.js";
let t0: any;
const inputs: number[] = [4, -1];
async function probe(input: number) {
  return await ((t0 = first(...[/*operand*/input]), /*call*/adder(/*arg*/note("step", 3))(t0)));
}
