// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_overloadedStep_logicalAnd_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, risky, shape } from "./harness.js";
const inputs: number[] = [4, 12];
function probe(input: number) {
  try {
    return flip() && /*call*/shape(risky(/*operand*/input))./*member*/length;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
