// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_stepAfterValue_callArgument_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, adder, resource } from "./harness.js";
let t0: any;
const inputs: number[] = [4, -1];
function probe(input: number) {
  using res = resource("res");
  return pack(note("a", 1), (t0 = note("operand", /*operand*/input), /*call*/adder(/*arg*/note("step", 3))(t0)), note("c", 3));
}
