// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_memberStep_jsxFragment_plain.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, tools, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [2, 6];
function probe(input: number) {
  return <>{note("before", "[")}{(t0 = note("operand", /*operand*/input), note("receiver", /*use*/tools)./*member*/twice(t0))}{note("after", "]")}</>;
}
