// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_memberStep_ifLetBody_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note, tools, read } from "./harness.js";
let t0: any;
const inputs: number[] = [2, 6];
function* probe(input: number): Generator<unknown, unknown, number> {
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, (t0 = (yield /*operand*/input), note("receiver", /*use*/tools)./*member*/twice(t0))];
  }
  return null;
}
