// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_nullishStep_jsxSpreadAttribute_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, flip, risky, double, lookup, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [10, 20];
function probe(input: number) {
  try {
    return <div {...{ value: (t0 = risky(/*operand*/input), (/*call*/lookup(flip()) ?? /*use*/double)(t0)) }} />;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
