// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_conditionalBranch_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, positive } from "./harness.js";
const inputs: number[] = [2.5, -3];
function* probe(input: number): Generator<unknown, unknown, number> {
  return flip() ? /*call*/positive((yield /*operand*/input))?./*member*/toFixed(2) : note("else", "skipped");
}
