// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_arrowBody_spread.tt; it shares the case's other units.
// @filename: main.ts
import { first, double, keep } from "./harness.js";
const inputs: number[] = [6, -2];
function probe(input: number) {
  const inner = (input: number) => double(/*call*/keep(first(...[/*operand*/input])));
  return inner(input);
}
