// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_arrowStep_getter_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
let t0: any;
const inputs: number[] = [8, 9];
function probe(input: number) {
  try {
    const holder = {
      get field() {
        return (t0 = note("operand", /*operand*/input), ((/*bind*/n: number) => note("arrow", /*use*/n + 1))(t0));
      },
    };
    return holder.field;
  } finally {
    note("finally", 0);
  }
}
