// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_objectProperty_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, double } from "./harness.js";
const inputs: number[] = [3, 12];
function probe(input: number) {
  return { a: note("a", 1), value: /*call2*/String(/*call*/double(note("operand", /*operand*/input)))./*member*/padStart(/*arg*/4, "*"), c: note("c", 3) };
}
