// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_logicalAnd_yield.tt; it shares the case's other units.
// @filename: main.ts
import { flip, double } from "./harness.js";
const inputs: number[] = [3, 12];
function* probe(input: number): Generator<unknown, unknown, number> {
  return flip() && /*call2*/String(/*call*/double((yield /*operand*/input)))./*member*/padStart(/*arg*/4, "*");
}
