// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_jsxFragment_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, first, element, Fragment } from "./harness.js";
const inputs: number[] = [123, 4];
function probe(input: number) {
  return <>{note("before", "[")}{(/*call*/String(first(...[/*operand*/input])) as string)./*member*/length}{note("after", "]")}</>;
}
