// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_memberStep_templateLiteral_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, tools, resource } from "./harness.js";
let t0: any;
const inputs: number[] = [2, 6];
function probe(input: number) {
  using res = resource("res");
  return `<${note("left", "L")}|${(t0 = note("operand", /*operand*/input), note("receiver", /*use*/tools)./*member*/twice(t0))}|${note("right", "R")}>`;
}
