// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_callStep_ifLetBody_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, double, read } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  try {
    const head = read(note("head", 1));
    if (head.kind === "Ok") {
      const n = head.value;
      return [n, /*call*/double(note("operand", /*operand*/input))];
    }
    return null;
  } finally {
    note("finally", 0);
  }
}
