// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_loopBody_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, double, keep, resource } from "./harness.js";
const inputs: number[] = [6, -2];
function probe(input: number) {
  using res = resource("res");
  const collected: unknown[] = [];
  for (let round = 0; round < 2; round++) {
    collected.push(double(/*call*/keep(note("operand", /*operand*/input))));
  }
  return collected;
}
