// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_overloadedStep_jsxFragment_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, first, shape, element, Fragment } from "./harness.js";
const inputs: number[] = [4, 12];
function probe(input: number) {
  return <>{note("before", "[")}{/*call*/shape(first(...[/*operand*/input]))./*member*/length}{note("after", "]")}</>;
}
