// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_nullish_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, box, positive } from "./harness.js";
const inputs: number[] = [2.5, -3];
function probe(input: number) {
  return (flip() ? null : note("left", "set")) ?? /*call*/positive(box(/*operand*/input)?.inner.value!)?./*member*/toFixed(2);
}
