// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_awaitOperand_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box } from "./harness.js";
const inputs: number[] = [123, 4];
async function probe(input: number) {
  return await ((/*call*/String(box(/*operand*/input)?.inner.value!) as string)./*member*/length);
}
