// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_jsxFragment_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, first, double, keep, element, Fragment } from "./harness.js";
const inputs: number[] = [6, -2];
function probe(input: number) {
  return <>{note("before", "[")}{double(/*call*/keep(first(...[/*operand*/input])))}{note("after", "]")}</>;
}
