// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalMemberStep_objectProperty_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, risky, maybe } from "./harness.js";
let t0: any;
const inputs: number[] = [3, 4, 5];
function probe(input: number) {
  try {
    return { a: note("a", 1), value: (t0 = risky(/*operand*/input), /*call*/maybe(/*arg*/flip())?./*member*/twice(t0)), c: note("c", 3) };
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
