// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_loopBody_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, double } from "./harness.js";
const inputs: number[] = [3, 12];
function probe(input: number) {
  try {
    const collected: unknown[] = [];
    for (let round = 0; round < 2; round++) {
      collected.push(/*call2*/String(/*call*/double(note("operand", /*operand*/input)))./*member*/padStart(/*arg*/4, "*"));
    }
    return collected;
  } finally {
    note("finally", 0);
  }
}
