// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_nullish_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip } from "./harness.js";
const inputs: number[] = [123, 4];
function probe(input: number) {
  try {
    return (flip() ? null : note("left", "set")) ?? (/*call*/String(note("operand", /*operand*/input)) as string)./*member*/length;
  } finally {
    note("finally", 0);
  }
}
