// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_stepAfterValue_jsxComponentProp_exception.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, risky, adder, Show, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [4, -1];
function probe(input: number) {
  try {
    return <Show /*attrHost*/value={(t0 = risky(/*operand*/input), /*call*/adder(/*arg*/note("step", 3))(t0))} />;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
