// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_callStep_jsxChild_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { later, double, element, Fragment } from "./harness.js";
const inputs: number[] = [2, 5];
async function probe(input: number) {
  return <p>{/*call*/double(await later(/*operand*/input))}</p>;
}
