// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_genericStep_jsxConditional_yield.ttx; it shares the case's other units.
// @filename: main.tsx
import { flip, double, keep, element, Fragment } from "./harness.js";
const inputs: number[] = [6, -2];
function* probe(input: number): Generator<unknown, unknown, number> {
  return <p>{flip() && double(/*call*/keep((yield /*operand*/input)))}</p>;
}
