// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_arrowStep_jsxChild_using.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, resource, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [8, 9];
function probe(input: number) {
  using res = resource("res");
  return <p>{(t0 = note("operand", /*operand*/input), ((/*bind*/n: number) => note("arrow", /*use*/n + 1))(t0))}</p>;
}
