// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_ifLetBody_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, double, read } from "./harness.js";
const inputs: number[] = [3, 12];
function probe(input: number) {
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, /*call2*/String(/*call*/double(first(...[/*operand*/input])))./*member*/padStart(/*arg*/4, "*")];
  }
  return null;
}
