// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_nullishStep_jsxTernary_optionalChain.ttx; it shares the case's other units.
// @filename: main.tsx
import { flip, box, double, lookup, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [10, 20];
function probe(input: number) {
  return <p>{flip() ? (t0 = box(/*operand*/input)?.inner.value!, (/*call*/lookup(flip()) ?? /*use*/double)(t0)) : <i>none</i>}</p>;
}
