// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_postfixStep_ifLetBody_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, read } from "./harness.js";
const inputs: number[] = [1.25, 7];
function probe(input: number) {
  using res = resource("res");
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, (note("operand", /*operand*/input))./*member*/toFixed(/*arg*/1)];
  }
  return null;
}
