// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_stepAfterValue_jsxConditional_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, later, flip, adder, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [4, -1];
async function probe(input: number) {
  return <p>{flip() && (t0 = await later(/*operand*/input), /*call*/adder(/*arg*/note("step", 3))(t0))}</p>;
}
