// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalMemberStep_declarationInitializer_await.tt; it shares the case's other units.
// @filename: main.ts
import { later, flip, maybe } from "./harness.js";
let t0: any;
const inputs: number[] = [3, 4, 5];
async function probe(input: number) {
  const value = (t0 = await later(/*operand*/input), /*call*/maybe(/*arg*/flip())?./*member*/twice(t0));
  return value;
}
