// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_callStep_awaitOperand_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box, double } from "./harness.js";
const inputs: number[] = [2, 5];
async function probe(input: number) {
  return await (/*call*/double(box(/*operand*/input)?.inner.value!));
}
