// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_memberStep_nullish_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, flip, tools } from "./harness.js";
let t0: any;
const inputs: number[] = [2, 6];
async function probe(input: number) {
  return (flip() ? null : note("left", "set")) ?? (t0 = await later(/*operand*/input), note("receiver", /*use*/tools)./*member*/twice(t0));
}
