// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_stepAfterValue_jsxFragment_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, adder, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [4, -1];
function probe(input: number) {
  try {
    return <>{note("before", "[")}{(t0 = note("operand", /*operand*/input), /*call*/adder(/*arg*/note("step", 3))(t0))}{note("after", "]")}</>;
  } finally {
    note("finally", 0);
  }
}
