// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_overloadedStep_arrowBody_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, shape } from "./harness.js";
const inputs: number[] = [4, 12];
function probe(input: number) {
  try {
    const inner = (input: number) => /*call*/shape(note("operand", /*operand*/input))./*member*/length;
    return inner(input);
  } finally {
    note("finally", 0);
  }
}
