// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_chain_jsxNested_using.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, double, resource, element, Fragment } from "./harness.js";
const inputs: number[] = [3, 12];
function probe(input: number) {
  using res = resource("res");
  return <ul><li>{note("first", 1)}</li><li>{/*call2*/String(/*call*/double(note("operand", /*operand*/input)))./*member*/padStart(/*arg*/4, "*")}</li></ul>;
}
