// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_arrowStep_jsxSpreadAttribute_yield.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [8, 9];
function* probe(input: number): Generator<unknown, unknown, number> {
  return <div {...{ value: (t0 = (yield /*operand*/input), ((/*bind*/n: number) => note("arrow", /*use*/n + 1))(t0)) }} />;
}
