// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_callStep_matchArm_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, risky, double } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  try {
    return (flip() ? /*call*/double(risky(/*operand*/input)) : note("other arm", 0));
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
