// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_assertionThenStep_jsxChild_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { later, element, Fragment } from "./harness.js";
const inputs: number[] = [123, 4];
async function probe(input: number) {
  return <p>{(/*call*/String(await later(/*operand*/input)) as string)./*member*/length}</p>;
}
