// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_curriedStd_jsxNested_finally.ttx; it shares the case's other units.
// @filename: main.tsx
import { note, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [5, 0];
function probe(input: number) {
  try {
    return <ul><li>{note("first", 1)}</li><li>{(t0 = note("operand", /*operand*/input) || null, t0 === null ? -1 : ((/*bind*/n: number) => note("map", /*use*/n * 3))(t0))}</li></ul>;
  } finally {
    note("finally", 0);
  }
}
