// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_nullishStep_jsxConditional_yield.ttx; it shares the case's other units.
// @filename: main.tsx
import { flip, double, lookup, element, Fragment } from "./harness.js";
let t0: any;
const inputs: number[] = [10, 20];
function* probe(input: number): Generator<unknown, unknown, number> {
  return <p>{flip() && (t0 = (yield /*operand*/input), (/*call*/lookup(flip()) ?? /*use*/double)(t0))}</p>;
}
