// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_postfixStep_declarationInitializer_yield.tt; it shares the case's other units.
// @filename: main.ts
const inputs: number[] = [1.25, 7];
function* probe(input: number): Generator<unknown, unknown, number> {
  const value = ((yield /*operand*/input))./*member*/toFixed(/*arg*/1);
  return value;
}
