// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_overloadedStep_callArgument_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, first, shape } from "./harness.js";
const inputs: number[] = [4, 12];
function probe(input: number) {
  return pack(note("a", 1), /*call*/shape(first(...[/*operand*/input]))./*member*/length, note("c", 3));
}
