// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_optionalTail_returnOperand_await.tt; it shares the case's other units.
// @filename: main.ts
import { later, positive } from "./harness.js";
const inputs: number[] = [2.5, -3];
async function probe(input: number) {
  return /*call*/positive(await later(/*operand*/input))?./*member*/toFixed(2);
}
