// Generated by scripts/generate-cases from tests/matrix/pipeline.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of pipeline_stepAfterValue_getter_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, adder } from "./harness.js";
let t0: any;
const inputs: number[] = [4, -1];
function probe(input: number) {
  try {
    const holder = {
      get field() {
        return (t0 = risky(/*operand*/input), /*call*/adder(/*arg*/note("step", 3))(t0));
      },
    };
    return holder.field;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
