// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_thenOnly_componentBody_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, first, read, element, Fragment } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    let seen: unknown = "none";
    { const t0 = /*call*/read(/*arg*/first(...[/*operand*/input]));
      if (t0.kind === "Ok") { const /*bind*/v = t0./*field*/value; seen = note("then", /*use*/v); } }
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
