// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_elseIfLetChain_componentBody_using.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, resource, read, element, Fragment } from "./harness.js";
const inputs: number[] = [4, -4];
function probe(input: number) {
  using res = resource("res");
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    let seen: unknown = "none";
    { const t0 = read(note("operand", /*operand*/input));
      if (t0.kind === "Ok") { const /*bind*/v = t0.value; seen = note("first", /*use*/v); } else { const t1 = /*call*/read(/*arg*/note("second", -2)); if (t1.kind === "Err") { const { /*bind2*/error } = t1; seen = note("second", /*use2*/error); } else { seen = "neither"; } } }
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
