// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_objectLiteralHead_componentBody_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, first, element, Fragment } from "./harness.js";
const inputs: number[] = [6, 9];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    let seen: unknown = "none";
    { const t0 = { kind: "Some" as const, value: first(...[/*operand*/input]) };
      if (t0.kind === "Some") { const /*bind*/v = t0.value; seen = note("some", /*use*/v); } }
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
