// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_thenOnly_nestedBlock_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, read } from "./harness.js";
const inputs: number[] = [2, -1];
async function probe(input: number) {
  {
    let seen: unknown = "none";
    { const t0 = /*call*/read(/*arg*/await later(/*operand*/input));
      if (t0.kind === "Ok") { const /*bind*/v = t0./*field*/value; seen = note("then", /*use*/v); } }
    return seen;
  }
}
