// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_thenOnly_ifBranch_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note, read } from "./harness.js";
const inputs: number[] = [2, -1];
function* probe(input: number): Generator<unknown, unknown, number> {
  if (note("enter", true)) {
    let seen: unknown = "none";
    { const t0 = /*call*/read(/*arg*/(yield /*operand*/input));
      if (t0.kind === "Ok") { const /*bind*/v = t0./*field*/value; seen = note("then", /*use*/v); } }
    return seen;
  }
  return "skipped";
}
