// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_exitInBody_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, read, report } from "./harness.js";
const inputs: number[] = [2, -2];
let input: number = inputs[0]!;
{ const t0 = read(await later(/*operand*/input));
  if (t0.kind === "Err") { const { /*bind*/error } = t0; note("error", /*use*/error); throw new Error("diverged"); } }
report("topLevel", input, text("passed"));
