// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_exitInBody_unbracedIf_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box, read } from "./harness.js";
const inputs: number[] = [2, -2];
function probe(input: number) {
  if (note("enter", true)) { const t0 = read(box(/*operand*/input)?.inner.value!);
    if (t0.kind === "Err") { const { /*bind*/error } = t0; note("error", /*use*/error); return "diverged"; } }
  return "passed";
}
