// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_withElse_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, read, report } from "./harness.js";
const inputs: number[] = [3, -3];
let input: number = inputs[0]!;
let seen: unknown = "none";
{ const t0 = read(await later(/*operand*/input));
  if (t0.kind === "Ok") { const /*bind*/v = t0.value; seen = note("then", /*use*/v); } else { seen = /*call*/note(/*arg*/"else", "missing"); } }
report("topLevel", input, text(seen));
