// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_exitInBody_resultBodyTemplateExit_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [2, -2];
function probe(input: number) {
  const block = (() => {
      try {
        const base = unwrap(read(note("base", 1)));
        { const t0 = read(first(...[/*operand*/input]));
          if (t0.kind === "Err") { const { /*bind*/error } = t0; note("error", /*use*/error); return ok(`<${base === 1 ? "one" : "many"}>`); } }
        return ok([base, "passed"]);
      } catch (error) {
        return caught(error);
      }
  })();
  return block;
}
