// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_withElse_forOfBody_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, read } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  const collected: unknown[] = [];
  for (const round of [0, 1]) {
    note("round", round);
    let seen: unknown = "none";
    { const t0 = read(first(...[/*operand*/input]));
      if (t0.kind === "Ok") { const /*bind*/v = t0.value; seen = note("then", /*use*/v); } else { seen = /*call*/note(/*arg*/"else", "missing"); } }
    collected.push(seen);
  }
  return collected;
}
