// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_objectLiteralHead_nestedBlock_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
const inputs: number[] = [6, 9];
function probe(input: number) {
  {
    let seen: unknown = "none";
    { const t0 = { kind: "Some" as const, value: box(/*operand*/input)?.inner.value! };
      if (t0.kind === "Some") { const /*bind*/v = t0.value; seen = note("some", /*use*/v); } }
    return seen;
  }
}
