// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_objectLiteralHead_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, report } from "./harness.js";
const inputs: number[] = [6, 9];
let input: number = inputs[0]!;
let seen: unknown = "none";
{ const t0 = { kind: "Some" as const, value: await later(/*operand*/input) };
  if (t0.kind === "Some") { const /*bind*/v = t0.value; seen = note("some", /*use*/v); } }
report("topLevel", input, text(seen));
