// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_withElse_staticBlock_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, read } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  try {
    class Holder {
      static field: unknown = "none";
      static {
        let seen: unknown = "none";
        { const t0 = read(risky(/*operand*/input));
          if (t0.kind === "Ok") { const /*bind*/v = t0.value; seen = note("then", /*use*/v); } else { seen = /*call*/note(/*arg*/"else", "missing"); } }
        Holder.field = seen;
      }
    }
    return Holder.field;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
