// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_orPattern_catchBlock_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, box } from "./harness.js";
type Token = { kind: "Num"; value: number } | { kind: "Neg"; value: number } | { kind: "Word"; text: string };
const Token = {
  Num: (value: number): Token => ({ kind: "Num" as const, value }),
  Neg: (value: number): Token => ({ kind: "Neg" as const, value }),
  Word: (text: string): Token => ({ kind: "Word" as const, text }),
};
const inputs: Token[] = [Token.Num(1), Token.Neg(-1), Token.Word("w")];
function probe(input: Token) {
  try {
    throw new Error(note("throw", "boom"));
  } catch (error) {
    let seen: unknown = "none";
    { const t0 = box(/*operand*/input)?.inner.value!;
      if (t0.kind === "Num" || t0.kind === "Neg") { const { /*bind*/value } = t0; seen = note("number", /*use*/value); } }
    return seen;
  }
}
