// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_withElse_componentBody_await.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, later, read, element, Fragment } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  async function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    let seen: unknown = "none";
    { const t0 = read(await later(/*operand*/input));
      if (t0.kind === "Ok") { const /*bind*/v = t0.value; seen = note("then", /*use*/v); } else { seen = /*call*/note(/*arg*/"else", "missing"); } }
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
