// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_exitInBody_matchBlockArmValueExit_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, read } from "./harness.js";
const inputs: number[] = [2, -2];
function probe(input: number) {
  note<boolean>("arm", true);
  const value = (() => {
      { const t0 = read(note("operand", /*operand*/input));
        if (t0.kind === "Err") { const { /*bind*/error } = t0; note("error", /*use*/error); return note("exit", 3) === 3 ? "three" : "other"; } }
      return "passed";
  })();
  return value;
}
