// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_thenOnly_constructorBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, read } from "./harness.js";
const inputs: number[] = [2, -1];
function probe(input: number) {
  try {
    class Holder {
      field: unknown = "none";
      constructor(input: number) {
        let seen: unknown = "none";
        { const t0 = /*call*/read(/*arg*/risky(/*operand*/input));
          if (t0.kind === "Ok") { const /*bind*/v = t0./*field*/value; seen = note("then", /*use*/v); } }
        this.field = seen;
      }
    }
    return new Holder(input).field;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
