// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_exitInBody_componentBody_plain.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, read, element, Fragment } from "./harness.js";
const inputs: number[] = [2, -2];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    { const t0 = read(note("operand", /*operand*/input));
      if (t0.kind === "Err") { const { /*bind*/error } = t0; note("error", /*use*/error); return <p>diverged</p>; } }
    return <p>{text("passed")}</p>;
  }
  return Card({ input });
}
