// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_withElse_matchBlockArm_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource, read } from "./harness.js";
const inputs: number[] = [3, -3];
function probe(input: number) {
  using res = resource("res");
  note<boolean>("arm", true);
  const value = (() => {
      let seen: unknown = "none";
      { const t0 = read(note("operand", /*operand*/input));
        if (t0.kind === "Ok") { const /*bind*/v = t0.value; seen = note("then", /*use*/v); } else { seen = /*call*/note(/*arg*/"else", "missing"); } }
      return seen;
  })();
  return value;
}
