// Generated by scripts/generate-cases from tests/matrix/ifLet.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of ifLet_nestedPattern_whileBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky } from "./harness.js";
type Maybe = { kind: "Some"; value: number } | { kind: "None" };
const Maybe = {
  Some: (value: number): Maybe => ({ kind: "Some" as const, value }),
  None: { kind: "None" } as const,
};
type Outcome = { kind: "Done"; value: Maybe } | { kind: "Failed"; error: string };
const Outcome = {
  Done: (value: Maybe): Outcome => ({ kind: "Done" as const, value }),
  Failed: (error: string): Outcome => ({ kind: "Failed" as const, error }),
};
const inputs: Outcome[] = [Outcome.Done(Maybe.Some(5)), Outcome.Done(Maybe.None), Outcome.Failed("gone")];
function probe(input: Outcome) {
  try {
    let collected: unknown = "none";
    while (note("test", true)) {
      let seen: unknown = "none";
      { const t0 = risky(/*operand*/input);
        if (t0.kind === "Done" && t0.value.kind === "Some") { const /*bind*/v = t0.value.value; seen = note("some", /*use*/v); } else { seen = "other"; } }
      collected = seen;
      break;
    }
    return collected;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
