// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_twoSteps_objectProperty_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, double, adder } from "./harness.js";
const inputs: number[] = [2, 5];
async function probe(input: number) {
  return { a: note("a", 1), value: ((second: (n: number) => number) => (v: number) => second(/*call*/double(v)))(/*call2*/adder(/*arg*/await later(/*operand*/input))), c: note("c", 3) };
}
