// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_oneStep_ifLetBody_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first, adder, read } from "./harness.js";
const inputs: number[] = [7, 1];
function probe(input: number) {
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, /*call*/adder(/*arg*/first(...[/*operand*/input]))];
  }
  return null;
}
