// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_memberLater_topLevel_using.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, adder, tools, resource, report } from "./harness.js";
const inputs: number[] = [2, 3];
let input: number = inputs[0]!;
using res = resource("res");
const top0 = ((head: (n: number) => number, receiver: typeof tools) => (v: number) => receiver./*member*/twice(head(v)))(adder(note("operand", /*operand*/input)), note("receiver", /*use*/tools));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((head: (n: number) => number, receiver: typeof tools) => (v: number) => receiver.twice(head(v)))(adder(note("operand", input)), note("receiver", tools));
report("topLevel", input, text(top1));
