// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_optionalLater_loopBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { later, flip, adder, tools, maybe } from "./harness.js";
const inputs: number[] = [4, 6, 8];
async function probe(input: number) {
  const collected: unknown[] = [];
  for (let round = 0; round < 2; round++) {
    collected.push(((head: (n: number) => number, receiver: typeof tools | undefined) => (v: number) => ((w: number) => receiver?./*member*/twice(w))(head(v)))(adder(await later(/*operand*/input)), /*call*/maybe(/*arg*/flip())));
  }
  return collected;
}
