// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_memberFirst_returnOperand_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder, tools } from "./harness.js";
const inputs: number[] = [2, 7];
function probe(input: number) {
  return ((receiver: typeof tools, second: (n: number) => number) => (v: number) => second(receiver./*member*/twice(v)))(note("receiver", /*use*/tools), /*call*/adder(note("operand", /*operand*/input)));
}
