// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_oneStep_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, later, adder, report } from "./harness.js";
const inputs: number[] = [7, 1];
let input: number = inputs[0]!;
const top0 = /*call*/adder(/*arg*/await later(/*operand*/input));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = adder(await later(input));
report("topLevel", input, text(top1));
