// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_memberLater_getter_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, adder, tools } from "./harness.js";
const inputs: number[] = [2, 3];
function probe(input: number) {
  try {
    const holder = {
      get field() {
        return ((head: (n: number) => number, receiver: typeof tools) => (v: number) => receiver./*member*/twice(head(v)))(adder(risky(/*operand*/input)), note("receiver", /*use*/tools));
      },
    };
    return holder.field;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
