// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_optionalLater_awaitOperand_spread.tt; it shares the case's other units.
// @filename: main.ts
import { flip, first, adder, tools, maybe } from "./harness.js";
const inputs: number[] = [4, 6, 8];
async function probe(input: number) {
  return await (((head: (n: number) => number, receiver: typeof tools | undefined) => (v: number) => ((w: number) => receiver?./*member*/twice(w))(head(v)))(adder(first(...[/*operand*/input])), /*call*/maybe(/*arg*/flip())));
}
