// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_memberLater_ifLetBody_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder, tools, read } from "./harness.js";
const inputs: number[] = [2, 3];
function* probe(input: number): Generator<unknown, unknown, number> {
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, ((head: (n: number) => number, receiver: typeof tools) => (v: number) => receiver./*member*/twice(head(v)))(adder((yield /*operand*/input)), note("receiver", /*use*/tools))];
  }
  return null;
}
