// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_optionalLater_declarationInitializer_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { flip, box, adder, tools, maybe } from "./harness.js";
const inputs: number[] = [4, 6, 8];
function probe(input: number) {
  const value = ((head: (n: number) => number, receiver: typeof tools | undefined) => (v: number) => ((w: number) => receiver?./*member*/twice(w))(head(v)))(adder(box(/*operand*/input)?.inner.value!), /*call*/maybe(/*arg*/flip()));
  return value;
}
