// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_firstStepExpression_topLevel_using.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, adder, resource, report } from "./harness.js";
const inputs: number[] = [3, -4];
let input: number = inputs[0]!;
using res = resource("res");
const top0 = ((head: (n: number) => number) => (v: number) => /*call2*/String(head(v)))(/*call*/adder(/*arg*/note("operand", /*operand*/input)));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((head: (n: number) => number) => (v: number) => String(head(v)))(adder(note("operand", input)));
report("topLevel", input, text(top1));
