// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_firstStepExpression_declarationInitializer_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box, adder } from "./harness.js";
const inputs: number[] = [3, -4];
function probe(input: number) {
  const value = ((head: (n: number) => number) => (v: number) => /*call2*/String(head(v)))(/*call*/adder(/*arg*/box(/*operand*/input)?.inner.value!));
  return value;
}
