// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_genericLater_awaitOperand_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, keep, adder, resource } from "./harness.js";
const inputs: number[] = [3, -4];
async function probe(input: number) {
  using res = resource("res");
  return await (((head: (n: number) => number) => (v: number) => /*call*/keep(head(v)))(adder(note("operand", /*operand*/input))));
}
