// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_postfixLater_logicalAnd_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, risky, adder } from "./harness.js";
const inputs: number[] = [1.5, 2];
function probe(input: number) {
  try {
    return flip() && ((head: (n: number) => number) => (v: number) => head(v)./*member*/toFixed(/*arg*/1))(adder(risky(/*operand*/input)));
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
