// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_firstStepExpression_method_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder, read } from "./harness.js";
const inputs: number[] = [3, -4];
function probe(input: number) {
  class Holder {
    tag = "holder";
    read(input: number) {
      note("this", this.tag);
      return ((head: (n: number) => number) => (v: number) => /*call2*/String(head(v)))(/*call*/adder(/*arg*/note("operand", /*operand*/input)));
    }
  }
  return new Holder().read(input);
}
