// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_twoSteps_callArgument_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, first, double, adder } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  return pack(note("a", 1), ((second: (n: number) => number) => (v: number) => second(/*call*/double(v)))(/*call2*/adder(/*arg*/first(...[/*operand*/input]))), note("c", 3));
}
