// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_postfixLater_arrowBody_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box, adder } from "./harness.js";
const inputs: number[] = [1.5, 2];
function probe(input: number) {
  const inner = (input: number) => ((head: (n: number) => number) => (v: number) => head(v)./*member*/toFixed(/*arg*/1))(adder(box(/*operand*/input)?.inner.value!));
  return inner(input);
}
