// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_postfixLater_matchArm_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, adder, resource } from "./harness.js";
const inputs: number[] = [1.5, 2];
function probe(input: number) {
  using res = resource("res");
  return (flip() ? ((head: (n: number) => number) => (v: number) => head(v)./*member*/toFixed(/*arg*/1))(adder(note("operand", /*operand*/input))) : note("other arm", 0));
}
