// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_memberFirst_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, later, adder, tools, report } from "./harness.js";
const inputs: number[] = [2, 7];
let input: number = inputs[0]!;
const top0 = ((receiver: typeof tools, second: (n: number) => number) => (v: number) => second(receiver./*member*/twice(v)))(note("receiver", /*use*/tools), /*call*/adder(await later(/*operand*/input)));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((receiver: typeof tools, second: (n: number) => number) => (v: number) => second(receiver.twice(v)))(note("receiver", tools), adder(await later(input)));
report("topLevel", input, text(top1));
