// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_genericLater_objectProperty_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note, keep, adder } from "./harness.js";
const inputs: number[] = [3, -4];
function* probe(input: number): Generator<unknown, unknown, number> {
  return { a: note("a", 1), value: ((head: (n: number) => number) => (v: number) => /*call*/keep(head(v)))(adder((yield /*operand*/input))), c: note("c", 3) };
}
