// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_overloadedLater_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, later, shape, adder, report } from "./harness.js";
const inputs: number[] = [2, 5];
let input: number = inputs[0]!;
const top0 = ((head: (n: number) => number) => (v: number) => /*call*/shape(head(v)))(adder(await later(/*operand*/input)));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((head: (n: number) => number) => (v: number) => shape(head(v)))(adder(await later(input)));
report("topLevel", input, text(top1));
