// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_oneStep_declarationInitializer_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder, resource } from "./harness.js";
const inputs: number[] = [7, 1];
function probe(input: number) {
  using res = resource("res");
  const value = /*call*/adder(/*arg*/note("operand", /*operand*/input));
  return value;
}
