// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_overloadedLater_objectProperty_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, shape, adder, resource } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  using res = resource("res");
  return { a: note("a", 1), value: ((head: (n: number) => number) => (v: number) => /*call*/shape(head(v)))(adder(note("operand", /*operand*/input))), c: note("c", 3) };
}
