// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_oneStep_matchArm_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, box, adder } from "./harness.js";
const inputs: number[] = [7, 1];
function probe(input: number) {
  return (flip() ? /*call*/adder(/*arg*/box(/*operand*/input)?.inner.value!) : note("other arm", 0));
}
