// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_twoSteps_arrowBody_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, double, adder } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  try {
    const inner = (input: number) => ((second: (n: number) => number) => (v: number) => second(/*call*/double(v)))(/*call2*/adder(/*arg*/note("operand", /*operand*/input)));
    return inner(input);
  } finally {
    note("finally", 0);
  }
}
