// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_firstStepExpression_ifLetBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, adder, read } from "./harness.js";
const inputs: number[] = [3, -4];
async function probe(input: number) {
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, ((head: (n: number) => number) => (v: number) => /*call2*/String(head(v)))(/*call*/adder(/*arg*/await later(/*operand*/input)))];
  }
  return null;
}
