// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_oneStep_awaitOperand_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder } from "./harness.js";
const inputs: number[] = [7, 1];
async function probe(input: number) {
  return await (/*call*/adder(/*arg*/note("operand", /*operand*/input)));
}
