// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_optionalLater_nullish_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, flip, adder, tools, maybe } from "./harness.js";
const inputs: number[] = [4, 6, 8];
async function probe(input: number) {
  return (flip() ? null : note("left", "set")) ?? ((head: (n: number) => number, receiver: typeof tools | undefined) => (v: number) => ((w: number) => receiver?./*member*/twice(w))(head(v)))(adder(await later(/*operand*/input)), /*call*/maybe(/*arg*/flip()));
}
