// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_firstStepExpression_conditionalBranch_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, adder, resource } from "./harness.js";
const inputs: number[] = [3, -4];
function probe(input: number) {
  using res = resource("res");
  return flip() ? ((head: (n: number) => number) => (v: number) => /*call2*/String(head(v)))(/*call*/adder(/*arg*/note("operand", /*operand*/input))) : note("else", "skipped");
}
