// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_postfixLater_declarationInitializer_await.tt; it shares the case's other units.
// @filename: main.ts
import { later, adder } from "./harness.js";
const inputs: number[] = [1.5, 2];
async function probe(input: number) {
  const value = ((head: (n: number) => number) => (v: number) => head(v)./*member*/toFixed(/*arg*/1))(adder(await later(/*operand*/input)));
  return value;
}
