// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_memberFirst_loopBody_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder, tools, resource } from "./harness.js";
const inputs: number[] = [2, 7];
function probe(input: number) {
  using res = resource("res");
  const collected: unknown[] = [];
  for (let round = 0; round < 2; round++) {
    collected.push(((receiver: typeof tools, second: (n: number) => number) => (v: number) => second(receiver./*member*/twice(v)))(note("receiver", /*use*/tools), /*call*/adder(note("operand", /*operand*/input))));
  }
  return collected;
}
