// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_overloadedLater_declarationInitializer_yield.tt; it shares the case's other units.
// @filename: main.ts
import { shape, adder } from "./harness.js";
const inputs: number[] = [2, 5];
function* probe(input: number): Generator<unknown, unknown, number> {
  const value = ((head: (n: number) => number) => (v: number) => /*call*/shape(head(v)))(adder((yield /*operand*/input)));
  return value;
}
