// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_overloadedLater_nullish_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, shape, adder } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  try {
    return (flip() ? null : note("left", "set")) ?? ((head: (n: number) => number) => (v: number) => /*call*/shape(head(v)))(adder(note("operand", /*operand*/input)));
  } finally {
    note("finally", 0);
  }
}
