// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_memberLater_returnOperand_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder, tools } from "./harness.js";
const inputs: number[] = [2, 3];
function probe(input: number) {
  try {
    return ((head: (n: number) => number, receiver: typeof tools) => (v: number) => receiver./*member*/twice(head(v)))(adder(note("operand", /*operand*/input)), note("receiver", /*use*/tools));
  } finally {
    note("finally", 0);
  }
}
