// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_postfixLater_topLevel_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { text, box, adder, report } from "./harness.js";
const inputs: number[] = [1.5, 2];
let input: number = inputs[0]!;
const top0 = ((head: (n: number) => number) => (v: number) => head(v)./*member*/toFixed(/*arg*/1))(adder(box(/*operand*/input)?.inner.value!));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((head: (n: number) => number) => (v: number) => head(v).toFixed(1))(adder(box(input)?.inner.value!));
report("topLevel", input, text(top1));
