// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_oneStep_returnOperand_await.tt; it shares the case's other units.
// @filename: main.ts
import { later, adder } from "./harness.js";
const inputs: number[] = [7, 1];
async function probe(input: number) {
  return /*call*/adder(/*arg*/await later(/*operand*/input));
}
