// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_oneStep_loopBody_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box, adder } from "./harness.js";
const inputs: number[] = [7, 1];
function probe(input: number) {
  const collected: unknown[] = [];
  for (let round = 0; round < 2; round++) {
    collected.push(/*call*/adder(/*arg*/box(/*operand*/input)?.inner.value!));
  }
  return collected;
}
