// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_twoSteps_ifLetBody_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, double, adder, read } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, ((second: (n: number) => number) => (v: number) => second(/*call*/double(v)))(/*call2*/adder(/*arg*/note("operand", /*operand*/input)))];
  }
  return null;
}
