// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_oneStep_nullish_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, flip, first, adder } from "./harness.js";
const inputs: number[] = [7, 1];
function probe(input: number) {
  return (flip() ? null : note("left", "set")) ?? /*call*/adder(/*arg*/first(...[/*operand*/input]));
}
