// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_genericLater_callArgument_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, risky, keep, adder } from "./harness.js";
const inputs: number[] = [3, -4];
function probe(input: number) {
  try {
    return pack(note("a", 1), ((head: (n: number) => number) => (v: number) => /*call*/keep(head(v)))(adder(risky(/*operand*/input))), note("c", 3));
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
