// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_postfixLater_method_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder, resource, read } from "./harness.js";
const inputs: number[] = [1.5, 2];
function probe(input: number) {
  using res = resource("res");
  class Holder {
    tag = "holder";
    read(input: number) {
      note("this", this.tag);
      return ((head: (n: number) => number) => (v: number) => head(v)./*member*/toFixed(/*arg*/1))(adder(note("operand", /*operand*/input)));
    }
  }
  return new Holder().read(input);
}
