// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_memberFirst_ifLetBody_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note, adder, tools, read } from "./harness.js";
const inputs: number[] = [2, 7];
function probe(input: number) {
  const head = read(note("head", 1));
  if (head.kind === "Ok") {
    const n = head.value;
    return [n, ((receiver: typeof tools, second: (n: number) => number) => (v: number) => second(receiver./*member*/twice(v)))(note("receiver", /*use*/tools), /*call*/adder(note("operand", /*operand*/input)))];
  }
  return null;
}
