// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_genericLater_getter_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box, keep, adder } from "./harness.js";
const inputs: number[] = [3, -4];
function probe(input: number) {
  const holder = {
    get field() {
      return ((head: (n: number) => number) => (v: number) => /*call*/keep(head(v)))(adder(box(/*operand*/input)?.inner.value!));
    },
  };
  return holder.field;
}
