// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_twoSteps_topLevel_spread.tt; it shares the case's other units.
// @filename: main.ts
import { text, first, double, adder, report } from "./harness.js";
const inputs: number[] = [2, 5];
let input: number = inputs[0]!;
const top0 = ((second: (n: number) => number) => (v: number) => second(/*call*/double(v)))(/*call2*/adder(/*arg*/first(...[/*operand*/input])));
report("topLevel", input, text(top0));
input = inputs[1]!;
const top1 = ((second: (n: number) => number) => (v: number) => second(double(v)))(adder(first(...[input])));
report("topLevel", input, text(top1));
