// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_oneStep_callArgument_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note, pack, adder } from "./harness.js";
const inputs: number[] = [7, 1];
function* probe(input: number): Generator<unknown, unknown, number> {
  return pack(note("a", 1), /*call*/adder(/*arg*/(yield /*operand*/input)), note("c", 3));
}
