// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_oneStep_declarationInitializer_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky, adder } from "./harness.js";
const inputs: number[] = [7, 1];
function probe(input: number) {
  try {
    const value = /*call*/adder(/*arg*/risky(/*operand*/input));
    return value;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
