// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_overloadedLater_getter_finally.tt; it shares the case's other units.
// @filename: main.ts
import { note, shape, adder } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  try {
    const holder = {
      get field() {
        return ((head: (n: number) => number) => (v: number) => /*call*/shape(head(v)))(adder(note("operand", /*operand*/input)));
      },
    };
    return holder.field;
  } finally {
    note("finally", 0);
  }
}
