// Generated by scripts/generate-cases from tests/matrix/flow.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of flow_twoSteps_method_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, double, adder, read } from "./harness.js";
const inputs: number[] = [2, 5];
function probe(input: number) {
  class Holder {
    tag = "holder";
    async read(input: number) {
      note("this", this.tag);
      return ((second: (n: number) => number) => (v: number) => second(/*call*/double(v)))(/*call2*/adder(/*arg*/await later(/*operand*/input)));
    }
  }
  return new Holder().read(input);
}
