// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_kindTag_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, later, report } from "./harness.js";
const inputs: number[] = [4, 9];
let input: number = inputs[0]!;
type Meta = { kind: "kind"; value: number } | { kind: "other" };
const Meta = {
  kind: (value: number): Meta => ({ kind: "kind" as const, value }),
  other: { kind: "other" } as const,
};
const seen = [/*use*/Meta./*member*/kind(/*arg*/await later(/*operand*/input)), Meta.other];
report("topLevel", input, text(seen));
