// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_exported_topLevel_plain.tt; it shares the case's other units.
// @filename: main.ts
import { text, note, report } from "./harness.js";
const inputs: number[] = [4, 9];
let input: number = inputs[0]!;
export type Pub = { kind: "Item"; n: number };
export const Pub = {
  Item: (n: number): Pub => ({ kind: "Item" as const, n }),
};
const seen = [/*use*/Pub./*member*/Item(/*arg*/note("operand", /*operand*/input))];
report("topLevel", input, text(seen));
