// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_emptyParentheses_componentBody_optionalChain.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, box, element, Fragment } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    type Tick = { kind: "Now" } | { kind: "Later"; at: number };
    const Tick = {
      Now: (): Tick => ({ kind: "Now" as const }),
      Later: (at: number): Tick => ({ kind: "Later" as const, at }),
    };
    const seen = [/*use*/Tick./*member*/Now(), Tick.Later(/*arg*/box(/*operand*/input)?.inner.value!)];
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
