// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_payloadCases_topLevel_await.tt; it shares the case's other units.
// @filename: main.ts
import { text, later, report } from "./harness.js";
const inputs: number[] = [4, 9];
let input: number = inputs[0]!;
type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number };
const Shape = {
  Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
  Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
};
const seen = [/*use*/Shape./*member*/Circle(/*arg*/await later(/*operand*/input)), Shape.Rect(await later(input), 2)];
report("topLevel", input, text(seen));
