// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_kindTag_componentBody_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, first, element, Fragment } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    type Meta = { kind: "kind"; value: number } | { kind: "other" };
    const Meta = {
      kind: (value: number): Meta => ({ kind: "kind" as const, value }),
      other: { kind: "other" } as const,
    };
    const seen = [/*use*/Meta./*member*/kind(/*arg*/first(...[/*operand*/input])), Meta.other];
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
