// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_generic_labeledBlock_await.tt; it shares the case's other units.
// @filename: main.ts
import { later } from "./harness.js";
const inputs: number[] = [4, 9];
async function probe(input: number) {
  let collected: unknown = "none";
  found: {
    type Tree<T> = { kind: "Leaf"; value: T } | { kind: "Node"; left: Tree<T>; right: Tree<T> };
    const Tree = {
      Leaf: <T>(value: T): Tree<T> => ({ kind: "Leaf" as const, value }),
      Node: <T>(left: Tree<T>, right: Tree<T>): Tree<T> => ({ kind: "Node" as const, left, right }),
    };
    const seen = /*use*/Tree./*member*/Node(Tree.Leaf(/*arg*/await later(/*operand*/input)), Tree.Node(Tree.Leaf(await later(input) + 1), Tree.Leaf(0)));
    collected = seen;
  }
  return collected;
}
