// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_emptyParentheses_switchClause_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  switch (note("discriminant", 1)) {
    case 1: {
      type Tick = { kind: "Now" } | { kind: "Later"; at: number };
      const Tick = {
        Now: (): Tick => ({ kind: "Now" as const }),
        Later: (at: number): Tick => ({ kind: "Later" as const, at }),
      };
      const seen = [/*use*/Tick./*member*/Now(), Tick.Later(/*arg*/box(/*operand*/input)?.inner.value!)];
      return seen;
    }
    default:
    return "default";
  }
}
