// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_kindTag_forOfBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later } from "./harness.js";
const inputs: number[] = [4, 9];
async function probe(input: number) {
  const collected: unknown[] = [];
  for (const round of [0, 1]) {
    note("round", round);
    type Meta = { kind: "kind"; value: number } | { kind: "other" };
    const Meta = {
      kind: (value: number): Meta => ({ kind: "kind" as const, value }),
      other: { kind: "other" } as const,
    };
    const seen = [/*use*/Meta./*member*/kind(/*arg*/await later(/*operand*/input)), Meta.other];
    collected.push(seen);
  }
  return collected;
}
