// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_unitCases_staticBlock_spread.tt; it shares the case's other units.
// @filename: main.ts
import { note, first } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  class Holder {
    static field: unknown = "none";
    static {
      type Dir = { kind: "North" } | { kind: "South" };
      const Dir = {
        North: { kind: "North" } as const,
        South: { kind: "South" } as const,
      };
      const seen = [/*use*/Dir./*member*/North, Dir.South, /*call*/note(/*arg*/"operand", first(...[/*operand*/input]))];
      Holder.field = seen;
    }
  }
  return Holder.field;
}
