// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_optionalField_forOfBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  try {
    const collected: unknown[] = [];
    for (const round of [0, 1]) {
      note("round", round);
      type Http = { kind: "Get"; url: string; timeout?: number } | { kind: "Head" };
      const Http = {
        Get: (url: string, timeout?: number): Http => ({ kind: "Get" as const, url, ...(timeout !== undefined ? { timeout } : {}) }),
        Head: { kind: "Head" } as const,
      };
      const seen = [/*use*/Http./*member*/Get("a"), Http.Get("b", /*arg*/risky(/*operand*/input)), Http.Get("c", undefined), Http.Head];
      collected.push(seen);
    }
    return collected;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
