// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_unitCases_arrowBlock_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  const inner = async (input: number) => {
    type Dir = { kind: "North" } | { kind: "South" };
    const Dir = {
      North: { kind: "North" } as const,
      South: { kind: "South" } as const,
    };
    const seen = [/*use*/Dir./*member*/North, Dir.South, /*call*/note(/*arg*/"operand", await later(/*operand*/input))];
    return seen;
  };
  return inner(input);
}
