// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_emptyParentheses_whileBody_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  try {
    let collected: unknown = "none";
    while (note("test", true)) {
      type Tick = { kind: "Now" } | { kind: "Later"; at: number };
      const Tick = {
        Now: (): Tick => ({ kind: "Now" as const }),
        Later: (at: number): Tick => ({ kind: "Later" as const, at }),
      };
      const seen = [/*use*/Tick./*member*/Now(), Tick.Later(/*arg*/risky(/*operand*/input))];
      collected = seen;
      break;
    }
    return collected;
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
