// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_emptyParentheses_nestedBlock_plain.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  {
    type Tick = { kind: "Now" } | { kind: "Later"; at: number };
    const Tick = {
      Now: (): Tick => ({ kind: "Now" as const }),
      Later: (at: number): Tick => ({ kind: "Later" as const, at }),
    };
    const seen = [/*use*/Tick./*member*/Now(), Tick.Later(/*arg*/note("operand", /*operand*/input))];
    return seen;
  }
}
