// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_kindTag_ifBranch_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  try {
    if (note("enter", true)) {
      type Meta = { kind: "kind"; value: number } | { kind: "other" };
      const Meta = {
        kind: (value: number): Meta => ({ kind: "kind" as const, value }),
        other: { kind: "other" } as const,
      };
      const seen = [/*use*/Meta./*member*/kind(/*arg*/risky(/*operand*/input)), Meta.other];
      return seen;
    }
    return "skipped";
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
