// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_generic_catchBlock_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  try {
    throw new Error(note("throw", "boom"));
  } catch (error) {
    type Tree<T> = { kind: "Leaf"; value: T } | { kind: "Node"; left: Tree<T>; right: Tree<T> };
    const Tree = {
      Leaf: <T>(value: T): Tree<T> => ({ kind: "Leaf" as const, value }),
      Node: <T>(left: Tree<T>, right: Tree<T>): Tree<T> => ({ kind: "Node" as const, left, right }),
    };
    const seen = /*use*/Tree./*member*/Node(Tree.Leaf(/*arg*/box(/*operand*/input)?.inner.value!), Tree.Node(Tree.Leaf(box(input)?.inner.value! + 1), Tree.Leaf(0)));
    return seen;
  }
}
