// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_payloadCases_componentBody_spread.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, first, element, Fragment } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number };
    const Shape = {
      Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
      Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
    };
    const seen = [/*use*/Shape./*member*/Circle(/*arg*/first(...[/*operand*/input])), Shape.Rect(first(...[input]), 2)];
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
