// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_emptyParentheses_labeledBlock_spread.tt; it shares the case's other units.
// @filename: main.ts
import { first } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  let collected: unknown = "none";
  found: {
    type Tick = { kind: "Now" } | { kind: "Later"; at: number };
    const Tick = {
      Now: (): Tick => ({ kind: "Now" as const }),
      Later: (at: number): Tick => ({ kind: "Later" as const, at }),
    };
    const seen = [/*use*/Tick./*member*/Now(), Tick.Later(/*arg*/first(...[/*operand*/input]))];
    collected = seen;
  }
  return collected;
}
