// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_optionalField_topLevel_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { text, box, report } from "./harness.js";
const inputs: number[] = [4, 9];
let input: number = inputs[0]!;
type Http = { kind: "Get"; url: string; timeout?: number } | { kind: "Head" };
const Http = {
  Get: (url: string, timeout?: number): Http => ({ kind: "Get" as const, url, ...(timeout !== undefined ? { timeout } : {}) }),
  Head: { kind: "Head" } as const,
};
const seen = [/*use*/Http./*member*/Get("a"), Http.Get("b", /*arg*/box(/*operand*/input)?.inner.value!), Http.Get("c", undefined), Http.Head];
report("topLevel", input, text(seen));
