// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_unitCases_componentBody_optionalChain.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, box, element, Fragment } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    type Dir = { kind: "North" } | { kind: "South" };
    const Dir = {
      North: { kind: "North" } as const,
      South: { kind: "South" } as const,
    };
    const seen = [/*use*/Dir./*member*/North, Dir.South, /*call*/note(/*arg*/"operand", box(/*operand*/input)?.inner.value!)];
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
