// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_payloadCases_switchClause_exception.tt; it shares the case's other units.
// @filename: main.ts
import { note, risky } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  try {
    switch (note("discriminant", 1)) {
      case 1: {
        type Shape = { kind: "Circle"; r: number } | { kind: "Rect"; w: number; h: number };
        const Shape = {
          Circle: (r: number): Shape => ({ kind: "Circle" as const, r }),
          Rect: (w: number, h: number): Shape => ({ kind: "Rect" as const, w, h }),
        };
        const seen = [/*use*/Shape./*member*/Circle(/*arg*/risky(/*operand*/input)), Shape.Rect(risky(input), 2)];
        return seen;
      }
      default:
      return "default";
    }
  } catch (error) {
    return note("caught", (error as Error).message);
  }
}
