// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_kindTag_resultBody_await.tt; it shares the case's other units.
// @filename: main.ts
import { note, later, ok, read, unwrap, caught } from "./harness.js";
const inputs: number[] = [4, 9];
async function probe(input: number) {
  const block = (await (async () => {
        try {
          const base = unwrap(read(note("base", 1)));
          type Meta = { kind: "kind"; value: number } | { kind: "other" };
          const Meta = {
            kind: (value: number): Meta => ({ kind: "kind" as const, value }),
            other: { kind: "other" } as const,
          };
          const seen = [/*use*/Meta./*member*/kind(/*arg*/await later(/*operand*/input)), Meta.other];
          return ok([base, seen]);
        } catch (error) {
          return caught(error);
        }
    })());
  return block;
}
