// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_matchedWhereDeclared_staticBlock_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { note, box } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  class Holder {
    static field: unknown = "none";
    static {
      type Op = { kind: "Add"; n: number } | { kind: "Neg" };
      const Op = {
        Add: (n: number): Op => ({ kind: "Add" as const, n }),
        Neg: { kind: "Neg" } as const,
      };
      const seen = [/*use*/Op./*member*/Add(box(/*operand*/input)?.inner.value!), Op.Neg].map((o) => { const t0 = o; if (t0.kind === "Add") { const { /*bind*/n } = t0; return note("add", /*use2*/n + 1); } return note("neg", 0); });
      Holder.field = seen;
    }
  }
  return Holder.field;
}
