// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_optionalField_functionBody_yield.tt; it shares the case's other units.
// @filename: main.ts
const inputs: number[] = [4, 9];
function* probe(input: number): Generator<unknown, unknown, number> {
  type Http = { kind: "Get"; url: string; timeout?: number } | { kind: "Head" };
  const Http = {
    Get: (url: string, timeout?: number): Http => ({ kind: "Get" as const, url, ...(timeout !== undefined ? { timeout } : {}) }),
    Head: { kind: "Head" } as const,
  };
  const seen = [/*use*/Http./*member*/Get("a"), Http.Get("b", /*arg*/(yield /*operand*/input)), Http.Get("c", undefined), Http.Head];
  return seen;
}
