// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_generic_ifBranch_using.tt; it shares the case's other units.
// @filename: main.ts
import { note, resource } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  using res = resource("res");
  if (note("enter", true)) {
    type Tree<T> = { kind: "Leaf"; value: T } | { kind: "Node"; left: Tree<T>; right: Tree<T> };
    const Tree = {
      Leaf: <T>(value: T): Tree<T> => ({ kind: "Leaf" as const, value }),
      Node: <T>(left: Tree<T>, right: Tree<T>): Tree<T> => ({ kind: "Node" as const, left, right }),
    };
    const seen = /*use*/Tree./*member*/Node(Tree.Leaf(/*arg*/note("operand", /*operand*/input)), Tree.Node(Tree.Leaf(note("operand", input) + 1), Tree.Leaf(0)));
    return seen;
  }
  return "skipped";
}
