// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_generic_whileBody_yield.tt; it shares the case's other units.
// @filename: main.ts
import { note } from "./harness.js";
const inputs: number[] = [4, 9];
function* probe(input: number): Generator<unknown, unknown, number> {
  let collected: unknown = "none";
  while (note("test", true)) {
    type Tree<T> = { kind: "Leaf"; value: T } | { kind: "Node"; left: Tree<T>; right: Tree<T> };
    const Tree = {
      Leaf: <T>(value: T): Tree<T> => ({ kind: "Leaf" as const, value }),
      Node: <T>(left: Tree<T>, right: Tree<T>): Tree<T> => ({ kind: "Node" as const, left, right }),
    };
    const seen = /*use*/Tree./*member*/Node(Tree.Leaf(/*arg*/(yield /*operand*/input)), Tree.Node(Tree.Leaf((yield input) + 1), Tree.Leaf(0)));
    collected = seen;
    break;
  }
  return collected;
}
