// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_optionalField_componentBody_plain.ttx; it shares the case's other units.
// @filename: main.tsx
import { text, note, element, Fragment } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  function Card(props: { input: number }) {
    const input = props./*memberProps*/input;
    type Http = { kind: "Get"; url: string; timeout?: number } | { kind: "Head" };
    const Http = {
      Get: (url: string, timeout?: number): Http => ({ kind: "Get" as const, url, ...(timeout !== undefined ? { timeout } : {}) }),
      Head: { kind: "Head" } as const,
    };
    const seen = [/*use*/Http./*member*/Get("a"), Http.Get("b", /*arg*/note("operand", /*operand*/input)), Http.Get("c", undefined), Http.Head];
    return <p>{text(seen)}</p>;
  }
  return Card({ input });
}
