// Generated by scripts/generate-cases from tests/matrix/variant.mjs and tests/matrix/editor.mjs; edit the spec, not this file.
// The TypeScript twin of variant_kindTag_nestedBlock_optionalChain.tt; it shares the case's other units.
// @filename: main.ts
import { box } from "./harness.js";
const inputs: number[] = [4, 9];
function probe(input: number) {
  {
    type Meta = { kind: "kind"; value: number } | { kind: "other" };
    const Meta = {
      kind: (value: number): Meta => ({ kind: "kind" as const, value }),
      other: { kind: "other" } as const,
    };
    const seen = [/*use*/Meta./*member*/kind(/*arg*/box(/*operand*/input)?.inner.value!), Meta.other];
    return seen;
  }
}
